// <auto-generated> Gerado por tools/StructGen a partir dos headers do cliente (rebang/source/shared).
// NÃO EDITAR: rode tools/StructGen/dump.sh e `dotnet run --project tools/StructGen`. </auto-generated>
// Layout idêntico ao MSVC x86 do cliente (conferido por tests/Pangya.Tests/StructLayoutTests.g.cs).
#pragma warning disable CS0169, CS0649, IDE1006
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Pangya.Protocol.KR645;

/// <summary>_SYSTEMTIME (16 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 16)]
public partial struct SYSTEMTIME
{
    public ushort wYear;
    public ushort wMonth;
    public ushort wDayOfWeek;
    public ushort wDay;
    public ushort wHour;
    public ushort wMinute;
    public ushort wSecond;
    public ushort wMilliseconds;
}

/// <summary>sRoomDetail (12 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 12)]
public partial struct sRoomDetail
{
    public byte holes;
    public uint gameTime;
    public byte map;
    public byte gameType;
    public byte holeOrder;
    public uint matchTypeId;
}

/// <summary>sPangYaUserInfo (269 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 269)]
public partial struct sPangYaUserInfo
{
    public ByteArray22 sID;
    public ByteArray22 sNick;
    public ByteArray21 sGuild;
    public ByteArray12 szEmblemName;
    public uint school;
    public uint dwIdentity;
    public uint dwGalleryGuid;
    public uint dwGuid;
    public UInt32Array3 dwRank;
    public uint dwGuildId;
    public uint dwEmblemVer;
    public byte Bits_DoTutorial;
    public uint DoTutorial { readonly get => ((uint)Bits_DoTutorial >> 0) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint gender { readonly get => ((uint)Bits_DoTutorial >> 1) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint manner { readonly get => ((uint)Bits_DoTutorial >> 2) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 2)) | ((value & 1u) << 2)); }
    public uint angelicWings { readonly get => ((uint)Bits_DoTutorial >> 3) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 3)) | ((value & 1u) << 3)); }
    public uint angelicWingsEffect { readonly get => ((uint)Bits_DoTutorial >> 4) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 4)) | ((value & 1u) << 4)); }
    public uint devilWings { readonly get => ((uint)Bits_DoTutorial >> 5) & 1u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(1u << 5)) | ((value & 1u) << 5)); }
    public uint RookieFEvent { readonly get => ((uint)Bits_DoTutorial >> 6) & 3u; set => Bits_DoTutorial = (byte)((Bits_DoTutorial & ~(3u << 6)) | ((value & 3u) << 6)); }
    public byte Bits_NewYearEvent;
    public uint NewYearEvent { readonly get => ((uint)Bits_NewYearEvent >> 0) & 1u; set => Bits_NewYearEvent = (byte)((Bits_NewYearEvent & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint Reserved { readonly get => ((uint)Bits_NewYearEvent >> 1) & 127u; set => Bits_NewYearEvent = (byte)((Bits_NewYearEvent & ~(127u << 1)) | ((value & 127u) << 1)); }
    public short iBongdariShopUsableTimes;
    public short iBongdariShopBonusTimes;
    public short iBongdariShopRemainedBonus;
    public uint dwPointPointEvent;
    public uint dwFlagBlock;
    public int iTimeBlock;
    public int nChannelingFlag;
    public ByteArray128 sDisplayID;
    public uint dwUID;
}

/// <summary>sPangYaUserStatistics (235 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 235)]
public partial struct sPangYaUserStatistics
{
    public uint dwDrive;
    public uint dwPutt;
    public uint dwVisitTime;
    public uint dwShotTime;
    public float fLongest;
    public uint dwPangya;
    public uint dwTimeOut;
    public uint dwOB;
    public uint dwDistance;
    public uint dwHole;
    public uint dwMatchHole;
    public ushort wHoleInOne;
    public ushort wBunker;
    public uint dwFairway;
    public ushort wAlbatross;
    public uint dwHoleIn;
    public uint dwPuttIn;
    public float fLongestPuttIn;
    public float fLongestChipIn;
    public uint dwExp;
    public byte Level;
    public long i64Pang;
    public int iTotalScore;
    public ByteArray6 cBestScore;
    public Int64Array6 i64MaxPang;
    public uint dwGameCount;
    public uint dwDisconnectCount;
    public uint dwTeamWin;
    public uint dwTeamGames;
    public uint dwLadderPoint;
    public uint dwLadderWin;
    public uint dwLadderLose;
    public uint dwLadderDraw;
    public uint dwLadderHoles;
    public uint nMannerCombo;
    public uint nMaxMannerCombo;
    public uint dwNoMannerGameCount;
    public long i64TotalSkinsPang;
    public uint dwSkinsWin;
    public uint dwSkinsLose;
    public uint dwSkinsGames;
    public int iStrikePoint;
    public ushort iAllInCount;
    public uint eventValue;
    public uint eventFlag;
    public uint dwSeasonCount;
    public long i64SumPang;
}

/// <summary>sTrophyStatistics (78 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 78)]
public partial struct sTrophyStatistics
{
    public UInt16Array3Array13 Trophy;
}

/// <summary>sUserEquip (108 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 108)]
public partial struct sUserEquip
{
    public uint guidCaddie;
    public uint guidChar;
    public uint guidClubSet;
    public uint tidBall;
    public UInt32Array10 tidItemSlot;
    public UInt32Array6 guidSkin;
    public UInt32Array6 tidSkin;
    public uint guidMascot;
}

/// <summary>sMapStatistics (43 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 43)]
public partial struct sMapStatistics
{
    public byte bMap;
    public uint dwDrive;
    public uint dwPutt;
    public uint dwHole;
    public uint dwFairway;
    public uint dwHoleIn;
    public uint dwPuttIn;
    public int iTotalScore;
    public sbyte cBestScore;
    public long i64MaxPang;
    public uint tidChar;
    public byte eventScore;
}

/// <summary>sMyInfo (2412 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 2412)]
public partial struct sMyInfo
{
    public ushort roomIndex;
    public sPangYaUserInfo info;
    public sPangYaUserStatistics stat;
    public sTrophyStatistics trophy;
    public sUserEquip userEquip;
    public sMapStatisticsArray20 mapStat;
    public sMapStatisticsArray20 classicMapStat;
}

/// <summary>sCharacterInfo (444 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 444)]
public partial struct sCharacterInfo
{
    public uint tid;
    public uint guid;
    public UInt32Array24 tidParts;
    public byte hairClr;
    public byte Bits_shirtsClr;
    public uint shirtsClr { readonly get => ((uint)Bits_shirtsClr >> 0) & 15u; set => Bits_shirtsClr = (byte)((Bits_shirtsClr & ~(15u << 0)) | ((value & 15u) << 0)); }
    public uint gift_flag { readonly get => ((uint)Bits_shirtsClr >> 4) & 15u; set => Bits_shirtsClr = (byte)((Bits_shirtsClr & ~(15u << 4)) | ((value & 15u) << 4)); }
    public ByteArray5 PCL;
    public sbyte Purchase;
    public UInt32Array5 tidAuxParts;
    public ByteArray9Array24 UccIndexList;
    public UInt32Array24 ItemIdList;
}

/// <summary>sCaddieInfo (25 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 25)]
public partial struct sCaddieInfo
{
    public uint guid;
    public uint tid;
    public uint tidPart;
    public byte Level;
    public uint Exp;
    public byte Bits_gift_flag;
    public uint gift_flag { readonly get => ((uint)Bits_gift_flag >> 0) & 1u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint Rent_flag { readonly get => ((uint)Bits_gift_flag >> 1) & 1u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(1u << 1)) | ((value & 1u) << 1)); }
    public ushort Remain_Date;
    public ushort Remain_Partdate;
    public sbyte Purchase;
    public byte byCheckCaddieWarning;
    public byte PCBangCaddie;
}

/// <summary>sClubInfo (18 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 18)]
public partial struct sClubInfo
{
    public uint guid;
    public uint tid;
    public Int16Array5 PCL;
}

/// <summary>sMascotInfo (63 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 63)]
public partial struct sMascotInfo
{
    public uint guid;
    public uint tid;
    public byte Level;
    public uint Exp;
    public ByteArray30 szMsg;
    public ushort Remain_Date;
    public sbyte Purchase;
    public SYSTEMTIME endDate;
    public byte PCBangMascot;
}

/// <summary>sUserInfo (2962 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 2962)]
public partial struct sUserInfo
{
    public ushort roomIndex;
    public sPangYaUserInfo info;
    public sPangYaUserStatistics stat;
    public sTrophyStatistics trophy;
    public sUserEquip userEquip;
    public sMapStatisticsArray20 mapStat;
    public sMapStatisticsArray20 classicMapStat;
    public sCharacterInfo charInfo;
    public sCaddieInfo caddieInfo;
    public sClubInfo clubInfo;
    public sMascotInfo mascotInfo;
}

/// <summary>sSpecialTrophy (12 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 12)]
public partial struct sSpecialTrophy
{
    public uint guid;
    public uint tid;
    public uint count;
}

/// <summary>sGuildTrophy (4 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 4)]
public partial struct sGuildTrophy
{
    public uint TypeID;
}

/// <summary>sUserPosition (75 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 75)]
public partial struct sUserPosition
{
    public ushort iRoomIdx;
    public int iRoomType;
    public int iServerGUID;
    public byte iChannelUid;
    public ByteArray64 csChannelName;
}

/// <summary>sItemInfo (168 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 168)]
public partial struct sItemInfo
{
    public uint guid;
    public uint tid;
    public int HourRemain;
    public Int16Array5 Common;
    public sbyte Purchase;
    public byte Bits_gift_flag;
    public uint gift_flag { readonly get => ((uint)Bits_gift_flag >> 0) & 1u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint Expired { readonly get => ((uint)Bits_gift_flag >> 1) & 1u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint ItemFlag { readonly get => ((uint)Bits_gift_flag >> 2) & 3u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(3u << 2)) | ((value & 3u) << 2)); }
    public uint ItemType { readonly get => ((uint)Bits_gift_flag >> 4) & 7u; set => Bits_gift_flag = (byte)((Bits_gift_flag & ~(7u << 4)) | ((value & 7u) << 4)); }
    public SYSTEMTIME ItemDate;
    public byte Bits_Reserve;
    public uint Reserve { readonly get => ((uint)Bits_Reserve >> 0) & 1u; set => Bits_Reserve = (byte)((Bits_Reserve & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint IsValid { readonly get => ((uint)Bits_Reserve >> 1) & 1u; set => Bits_Reserve = (byte)((Bits_Reserve & ~(1u << 1)) | ((value & 1u) << 1)); }
    public ByteArray41 ItemName;
    public ByteArray9 UccIndex;
    public byte status;
    public ushort Seq;
    public ByteArray22 CopierNick;
    public UInt32Array12 attachCard;
    public ushort CharacterSlotNum;
    public ushort CaddieSlotNum;
}

/// <summary>GUILD_HISTORY (49 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 49)]
public partial struct GUILD_HISTORY
{
    public int index;
    public uint guildUID;
    public ByteArray21 guildName;
    public int state;
    public SYSTEMTIME time;
}

/// <summary>GUILD_USER_INFO (281 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 281)]
public partial struct GUILD_USER_INFO
{
    public uint guildUID;
    public ByteArray21 guildName;
    public int guildPang;
    public int guildPoint;
    public int memberCount;
    public ByteArray12 guildMark;
    public ByteArray101 notice;
    public ByteArray101 introduce;
    public int classIdx;
    public uint masterUID;
    public ByteArray22 masterNickname;
}

/// <summary>GUILD_INFO (297 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 297)]
public partial struct GUILD_INFO
{
    public uint guildUID;
    public ByteArray21 guildName;
    public int guildPang;
    public int guildPoint;
    public int memberCount;
    public ByteArray12 guildMark;
    public ByteArray101 notice;
    public ByteArray101 introduce;
    public int classIdx;
    public uint masterUID;
    public ByteArray22 masterNickname;
    public SYSTEMTIME createTime;
}

/// <summary>GUILD_LIST (196 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 196)]
public partial struct GUILD_LIST
{
    public uint guildUID;
    public ByteArray21 guildName;
    public int guildPang;
    public int guildPoint;
    public int memberCount;
    public SYSTEMTIME createTime;
    public ByteArray101 introduce;
    public uint unknown9a;
    public uint masterUID;
    public ByteArray22 masterNickname;
    public ByteArray12 guildMark;
}

/// <summary>GUILD_USER_LIST (81 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 81)]
public partial struct GUILD_USER_LIST
{
    public uint guildUID;
    public uint userUID;
    public int classIdx;
    public ByteArray25 message;
    public ByteArray21 guildName;
    public ByteArray22 nickname;
    public byte online;
}

/// <summary>GUILD_USER_MSN_LIST (55 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 55)]
public partial struct GUILD_USER_MSN_LIST
{
    public uint userUID;
    public uint guildUID;
    public byte sex;
    public ByteArray22 userID;
    public ByteArray22 nickname;
    public byte unknown35;
    public byte online;
}

/// <summary>sTreasureHunt (11 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 11)]
public partial struct sTreasureHunt
{
    public uint dwUID;
    public uint dwTid;
    public ushort wCount;
    public byte byItemType;
}

/// <summary>sTreasureGift (21 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 21)]
public partial struct sTreasureGift
{
    public uint dwUID;
    public uint dwTid;
    public uint dwItemGuid;
    public ushort wCount;
    public byte byItemType;
    public int iHourRemain;
    public ushort reserved;
}

/// <summary>sTreasureItem (5 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 5)]
public partial struct sTreasureItem
{
    public byte byMapIndex;
    public uint dwGauge;
}

/// <summary>stGameClass (8 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 8)]
public partial struct stGameClass
{
    public int style;
    public byte gameType;
}

/// <summary>EncryptKey (16 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 16)]
public partial struct EncryptKey
{
    public ByteArray16 m_byKey;
}

/// <summary>sUserInfoExt (3986 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 3986)]
public partial struct sUserInfoExt
{
    public ushort roomIndex;
    public sPangYaUserInfo info;
    public sPangYaUserStatistics stat;
    public sTrophyStatistics trophy;
    public sUserEquip userEquip;
    public sMapStatisticsArray20 mapStat;
    public sMapStatisticsArray20 classicMapStat;
    public sCharacterInfo charInfo;
    public sCaddieInfo caddieInfo;
    public sClubInfo clubInfo;
    public sMascotInfo mascotInfo;
    public ByteArray1024 ext;
}

/// <summary>sUserMatchHistory (52 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 52)]
public partial struct sUserMatchHistory
{
    public int nGender;
    public ByteArray22 szNickName;
    public ByteArray22 szLoginID;
    public uint dwUID;
}

/// <summary>sLevelUpDone (3 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 3)]
public partial struct sLevelUpDone
{
    public byte bDone;
    public byte bLevel;
    public byte bItemType;
}

/// <summary>sBriefUserInfo (196 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 196)]
public partial struct sBriefUserInfo
{
    public uint dwUid;
    public uint dwGuid;
    public ushort roomIndex;
    public ByteArray22 sNick;
    public byte level;
    public uint dwIdentity;
    public uint dwTitle;
    public uint dwLadderPoint;
    public byte Bits_bSleep;
    public uint bSleep { readonly get => ((uint)Bits_bSleep >> 0) & 1u; set => Bits_bSleep = (byte)((Bits_bSleep & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint gender { readonly get => ((uint)Bits_bSleep >> 1) & 7u; set => Bits_bSleep = (byte)((Bits_bSleep & ~(7u << 1)) | ((value & 7u) << 1)); }
    public uint manner { readonly get => ((uint)Bits_bSleep >> 4) & 1u; set => Bits_bSleep = (byte)((Bits_bSleep & ~(1u << 4)) | ((value & 1u) << 4)); }
    public uint angelicWings { readonly get => ((uint)Bits_bSleep >> 5) & 1u; set => Bits_bSleep = (byte)((Bits_bSleep & ~(1u << 5)) | ((value & 1u) << 5)); }
    public uint Reserve { readonly get => ((uint)Bits_bSleep >> 6) & 3u; set => Bits_bSleep = (byte)((Bits_bSleep & ~(3u << 6)) | ((value & 3u) << 6)); }
    public uint m_GuildId;
    public ByteArray12 szEmblemName;
    public ushort state;
    public int nChannelingFlag;
    public ByteArray128 reserved;
}

/// <summary>sGuildRoomInfo (74 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 74)]
public partial struct sGuildRoomInfo
{
    public UInt32Array2 nGuildID;
    public ByteArray21Array2 szName;
    public ByteArray12Array2 szEmblemName;
}

/// <summary>sRoomInfo (178 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 178)]
public partial struct sRoomInfo
{
    public ByteArray32 title;
    public ByteArray16 password;
    public byte bPublic;
    public byte bAvailable;
    public byte bIntrusion;
    public byte nUserLimit;
    public byte nUserNum;
    public EncryptKey RoomKey;
    public byte nGalleryNum;
    public byte nGalleryLimit;
    public byte nHole;
    public byte gameType;
    public ushort roomGuid;
    public byte holeType;
    public byte mapType;
    public uint shotTimeLimit;
    public uint gameTimeLimit;
    public uint tidMatch;
    public byte bSleep;
    public byte bAdminMaster;
    public sGuildRoomInfo GuildInfo;
    public uint pangMultiply;
    public uint expMultiply;
    public int masterUID;
    public byte realGameType;
}

/// <summary>sSlotInfo (338 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 338)]
public partial struct sSlotInfo
{
    public uint dwGuid;
    public ByteArray22 sNick;
    public ByteArray21 sGuild;
    public byte connectionRank;
    public uint dwIdentity;
    public uint dwTitle;
    public uint tidChar;
    public UInt32Array6 tidSkin;
    public byte Bits_bTeam;
    public uint bTeam { readonly get => ((uint)Bits_bTeam >> 0) & 3u; set => Bits_bTeam = (byte)((Bits_bTeam & ~(3u << 0)) | ((value & 3u) << 0)); }
    public uint bSleep { readonly get => ((uint)Bits_bTeam >> 2) & 1u; set => Bits_bTeam = (byte)((Bits_bTeam & ~(1u << 2)) | ((value & 1u) << 2)); }
    public uint bMaster { readonly get => ((uint)Bits_bTeam >> 3) & 3u; set => Bits_bTeam = (byte)((Bits_bTeam & ~(3u << 3)) | ((value & 3u) << 3)); }
    public uint gender { readonly get => ((uint)Bits_bTeam >> 5) & 7u; set => Bits_bTeam = (byte)((Bits_bTeam & ~(7u << 5)) | ((value & 7u) << 5)); }
    public byte Bits_manner;
    public uint manner { readonly get => ((uint)Bits_manner >> 0) & 1u; set => Bits_manner = (byte)((Bits_manner & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint bReady { readonly get => ((uint)Bits_manner >> 1) & 1u; set => Bits_manner = (byte)((Bits_manner & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint stateReserved { readonly get => ((uint)Bits_manner >> 2) & 63u; set => Bits_manner = (byte)((Bits_manner & ~(63u << 2)) | ((value & 63u) << 2)); }
    public byte level;
    public byte Bits_angelicWings;
    public uint angelicWings { readonly get => ((uint)Bits_angelicWings >> 0) & 1u; set => Bits_angelicWings = (byte)((Bits_angelicWings & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint angelicWingsEffect { readonly get => ((uint)Bits_angelicWings >> 1) & 1u; set => Bits_angelicWings = (byte)((Bits_angelicWings & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint Reserved { readonly get => ((uint)Bits_angelicWings >> 2) & 63u; set => Bits_angelicWings = (byte)((Bits_angelicWings & ~(63u << 2)) | ((value & 63u) << 2)); }
    public byte ladderGrade;
    public uint GuildId;
    public ByteArray12 szEmblemName;
    public uint dwUserUID;
    public uint state;
    public ushort subRoomIndex;
    public uint action;
    public SingleArray3 location;
    public uint iStateTrade;
    public ByteArray64 strTradeTitle;
    public uint tidMascot;
    public ByteArray2 pangma;
    public uint nChannelingFlag;
    public ByteArray128 sDisplayID;
    public byte Bits_IsInvite;
    public uint IsInvite { readonly get => ((uint)Bits_IsInvite >> 0) & 1u; set => Bits_IsInvite = (byte)((Bits_IsInvite & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint guestReserved { readonly get => ((uint)Bits_IsInvite >> 1) & 127u; set => Bits_IsInvite = (byte)((Bits_IsInvite & ~(127u << 1)) | ((value & 127u) << 1)); }
}

/// <summary>sChannelInfo (77 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 77)]
public partial struct sChannelInfo
{
    public ByteArray64 Name;
    public ushort Max_Num;
    public ushort Current_Num;
    public byte Uid;
    public uint Type;
    public int Property;
}

/// <summary>sGameServerInfo (92 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 92)]
public partial struct sGameServerInfo
{
    public ByteArray40 name;
    public uint id;
    public int maxUser;
    public int curUser;
    public ByteArray18 addr;
    public int port;
    public uint property;
    public int angelicWingsNum;
    public uint eventFlags;
    public uint eventValue;
    public ushort iconIndex;
}

/// <summary>sFriend (141 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 141)]
public partial struct sFriend
{
    public ByteArray22 NickName;
    public ByteArray11 szAlias;
    public uint Uid;
    public uint Guid;
    public uint Server;
    public uint dwGuildId;
    public ByteArray12 szEmblemName;
    public sUserPosition userPosition;
    public byte State;
    public byte Channel;
    public byte GameLevel;
    public byte Bits_Gender;
    public uint Gender { readonly get => ((uint)Bits_Gender >> 0) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint IsLogOn { readonly get => ((uint)Bits_Gender >> 1) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint IsAccept { readonly get => ((uint)Bits_Gender >> 2) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 2)) | ((value & 1u) << 2)); }
    public uint IsAgree { readonly get => ((uint)Bits_Gender >> 3) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 3)) | ((value & 1u) << 3)); }
    public uint IsBlock { readonly get => ((uint)Bits_Gender >> 4) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 4)) | ((value & 1u) << 4)); }
    public uint IsPlay { readonly get => ((uint)Bits_Gender >> 5) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 5)) | ((value & 1u) << 5)); }
    public uint IsDive { readonly get => ((uint)Bits_Gender >> 6) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 6)) | ((value & 1u) << 6)); }
    public uint IsBusy { readonly get => ((uint)Bits_Gender >> 7) & 1u; set => Bits_Gender = (byte)((Bits_Gender & ~(1u << 7)) | ((value & 1u) << 7)); }
    public byte Bits_PangyaFriend;
    public uint PangyaFriend { readonly get => ((uint)Bits_PangyaFriend >> 0) & 1u; set => Bits_PangyaFriend = (byte)((Bits_PangyaFriend & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint GuildFriend { readonly get => ((uint)Bits_PangyaFriend >> 1) & 1u; set => Bits_PangyaFriend = (byte)((Bits_PangyaFriend & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint IsBlocked { readonly get => ((uint)Bits_PangyaFriend >> 2) & 1u; set => Bits_PangyaFriend = (byte)((Bits_PangyaFriend & ~(1u << 2)) | ((value & 1u) << 2)); }
    public uint Reserved { readonly get => ((uint)Bits_PangyaFriend >> 3) & 31u; set => Bits_PangyaFriend = (byte)((Bits_PangyaFriend & ~(31u << 3)) | ((value & 31u) << 3)); }
}

/// <summary>sNoteInfo (109 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 109)]
public partial struct sNoteInfo
{
    public uint uid;
    public ushort reserved;
    public ByteArray22 sNick;
    public ByteArray64 sNote;
    public ByteArray16 sTime;
    public byte bReply;
}

/// <summary>sMailIncludeItem (53 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 53)]
public partial struct sMailIncludeItem
{
    public uint dwIDX;
    public uint dwTID;
    public byte btItemType;
    public int iCount;
    public int iTimeCount;
    public Int16Array5 soCom;
    public ushort CharacterSlotNum;
    public ushort CaddieSlotNum;
    public uint dwSetTID;
    public int iSetItemCount;
    public ByteArray9 csUCCIndex;
    public uint reserved30;
    public byte reserved34;
}

/// <summary>sMailInfoBrief (194 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 194)]
public partial struct sMailInfoBrief
{
    public uint id;
    public ByteArray22 sender;
    public ByteArray110 reserved;
    public byte bRead;
    public int itemCount;
    public sMailIncludeItem item;
}

/// <summary>sGiftInfo (251 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 251)]
public partial struct sGiftInfo
{
    public uint guid;
    public uint tid;
    public ushort Arg0;
    public ByteArray128 sFromID;
    public ByteArray80 sMsg;
    public ByteArray32 sDate;
    public byte ItemType;
}

/// <summary>sPouchPrize (20 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 20)]
public partial struct sPouchPrize
{
    public uint dwTid;
    public uint dwGuid;
    public int iCount;
    public uint dwFlag1;
    public uint dwFlag2;
}

/// <summary>sApproachResultData (24 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 24)]
public partial struct sApproachResultData
{
    public byte bExit;
    public uint dwGUID;
    public uint dwRealUID;
    public byte byRank;
    public uint dwPrizeCount;
    public uint dwRemainDistance;
    public uint dwRemainTime;
    public byte byRankPrize;
    public byte byLuckPrize;
}

/// <summary>CUTIN_ANI_STYPEINFO (184 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 184)]
public partial struct CUTIN_ANI_STYPEINFO
{
    public int PosType;
    public int CharType;
    public int BgType;
    public int PatternType;
    public int TextType;
    public int OutType;
    public ByteArray40 szCharTex;
    public ByteArray40 szBgTex;
    public ByteArray40 szPattern;
    public ByteArray40 szText;
}

/// <summary>GimmickDispositionInformation (20 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 20)]
public partial struct GimmickDispositionInformation
{
    public int type;
    public uint index;
    public int flag;
    public uint unknownC;
    public byte hole;
}

/// <summary>sSCardAvilityPeriodInfo (65 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 65)]
public partial struct sSCardAvilityPeriodInfo
{
    public uint uid;
    public uint tid;
    public uint partsTid;
    public uint partsUid;
    public int Avility;
    public uint AvilityValue;
    public int slotNum;
    public SYSTEMTIME useStartTime;
    public SYSTEMTIME useEndTime;
    public int cardType;
    public byte valid;
}

/// <summary>sCards (58 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 58)]
public partial struct sCards
{
    public uint uid;
    public uint typeId;
    public ByteArray12 reserved08;
    public int count;
    public ByteArray32 reserved18;
    public byte type;
    public byte reserved39;
}

/// <summary>sItemAttachCard (8 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 8)]
public partial struct sItemAttachCard
{
    public uint typeId;
    public uint id;
}

/// <summary>sCaddieReportData (127 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 127)]
public partial struct sCaddieReportData
{
    public uint uid;
    public long pang;
    public long bonusPang;
    public uint roomType;
    public uint exp;
    public uint mascotTypeId;
    public byte premium;
    public sbyte pangItem;
    public ushort level;
    public ByteArray2 reserved24;
    public sbyte score;
    public byte awardFlag;
    public byte eventType;
    public ByteArray22 reserved29;
    public ByteArray22 nickname;
    public ByteArray4 reserved55;
    public uint guildUID;
    public ByteArray12 guildMark;
    public byte gameType;
    public ByteArray3 reserved6a;
    public byte team;
    public byte eventFlag;
    public ByteArray16 reserved6f;
}

/// <summary>sRoomUserInfo (18 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 18)]
public partial struct sRoomUserInfo
{
    public uint uid;
    public byte level;
    public byte Bits_hole;
    public uint hole { readonly get => ((uint)Bits_hole >> 0) & 31u; set => Bits_hole = (byte)((Bits_hole & ~(31u << 0)) | ((value & 31u) << 0)); }
    public uint reserved05 { readonly get => ((uint)Bits_hole >> 5) & 7u; set => Bits_hole = (byte)((Bits_hole & ~(7u << 5)) | ((value & 7u) << 5)); }
    public uint capability;
    public ByteArray4 reserved0a;
    public uint ladderPoint;
}

/// <summary>sGuildMatchFlagInfo (46 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 46)]
public partial struct sGuildMatchFlagInfo
{
    public ByteArray46 reserved;
}

/// <summary>sMapEventInfo (40 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 40)]
public partial struct sMapEventInfo
{
    public ByteArray40 reserved;
}

/// <summary>sBurnningSpCard (20 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 20)]
public partial struct sBurnningSpCard
{
    public ByteArray20 reserved;
}

/// <summary>GuildMemberInfo_t (64 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 64)]
public partial struct GuildMemberInfo_t
{
    public ByteArray64 reserved;
}

/// <summary>sFurniture_List (27 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 27)]
public partial struct sFurniture_List
{
    public uint id;
    public uint typeId;
    public ushort reserved;
    public float x;
    public float y;
    public float z;
    public float r;
    public byte Bits_bArrange;
    public uint bArrange { readonly get => ((uint)Bits_bArrange >> 0) & 1u; set => Bits_bArrange = (byte)((Bits_bArrange & ~(1u << 0)) | ((value & 1u) << 0)); }
}

/// <summary>sAwardItem (8 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 8)]
public partial struct sAwardItem
{
    public uint uid;
    public int pang;
}

/// <summary>sRealMyRoomAuthority (107 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 107)]
public partial struct sRealMyRoomAuthority
{
    public uint ownerUID;
    public ushort unknown4;
    public byte bPrivate;
    public ByteArray100 password;
}

/// <summary>sBuyItemResult (38 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 38)]
public partial struct sBuyItemResult
{
    public uint Typeid;
    public uint guid;
    public ushort Time;
    public byte ItemType;
    public ushort Count;
    public SYSTEMTIME endDate;
    public ByteArray9 UccIndex;
}

/// <summary>sBuyItem (16 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 16)]
public partial struct sBuyItem
{
    public int Idx;
    public uint TypeCode;
    public ushort DayCount;
    public short sChildItemIndex;
    public uint ItemCount;
}

/// <summary>sTradeItem (170 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 170)]
public partial struct sTradeItem
{
    public int iIndex;
    public uint dwTid;
    public uint dwGuid;
    public int iNum;
    public byte byItemType;
    public ushort wTime;
    public long i64Price;
    public uint dwUpgradeCost;
    public Int16Array5 arrEnchant;
    public ushort wFlagTradeLimit;
    public ByteArray9 UccIndex;
    public ushort Seq;
    public byte status;
    public UInt32Array4Array3 attachCardTid;
    public ushort CharacterSlotNum;
    public ushort CaddieSlotNum;
    public ByteArray41 ItemName;
    public ByteArray22 CopierNick;
}

/// <summary>sStallSlot (193 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 193)]
public partial struct sStallSlot
{
    public uint stallKey;
    public byte Idx;
    public sTradeItem itemData;
    public SYSTEMTIME time;
    public byte IsPermanence;
    public byte IsValid;
}

/// <summary>sStall (2343 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 2343)]
public partial struct sStall
{
    public uint typeID;
    public uint stallKey;
    public byte state;
    public byte maxSlotNum;
    public byte useSlotNum;
    public sStallSlotArray12 slotList;
    public SYSTEMTIME time;
}

/// <summary>sStoredItemInfo (174 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 174)]
public partial struct sStoredItemInfo
{
    public uint dwStorageID;
    public sTradeItem itemInfo;
}

/// <summary>sSaleItem (94 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 94)]
public partial struct sSaleItem
{
    public uint ownerUID;
    public ByteArray22 nickname;
    public uint typeId;
    public long price;
    public ushort count;
    public byte bOpen;
    public ByteArray53 reserved;
}

/// <summary>sCardStack (14 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 14)]
public partial struct sCardStack
{
    public uint uid;
    public uint typeId;
    public int count;
    public byte bValid;
    public byte unknownD;
}

/// <summary>IFF_ITEM_COMMON (144 bytes).</summary>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 144)]
public partial struct IFF_ITEM_COMMON
{
    public byte Final;
    public uint TypeId;
    public ByteArray40 Name;
    public byte Bits_Level;
    public uint Level { readonly get => ((uint)Bits_Level >> 0) & 127u; set => Bits_Level = (byte)((Bits_Level & ~(127u << 0)) | ((value & 127u) << 0)); }
    public uint IsUnderLvl { readonly get => ((uint)Bits_Level >> 7) & 1u; set => Bits_Level = (byte)((Bits_Level & ~(1u << 7)) | ((value & 1u) << 7)); }
    public ByteArray40 Icon;
    public uint Price;
    public uint SalePrice;
    public uint UsedPrice;
    public byte Bits_IsCash;
    public uint IsCash { readonly get => ((uint)Bits_IsCash >> 0) & 1u; set => Bits_IsCash = (byte)((Bits_IsCash & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint IsSalable { readonly get => ((uint)Bits_IsCash >> 1) & 15u; set => Bits_IsCash = (byte)((Bits_IsCash & ~(15u << 1)) | ((value & 15u) << 1)); }
    public uint InStock { readonly get => ((uint)Bits_IsCash >> 5) & 7u; set => Bits_IsCash = (byte)((Bits_IsCash & ~(7u << 5)) | ((value & 7u) << 5)); }
    public byte Bits_New;
    public uint New { readonly get => ((uint)Bits_New >> 0) & 1u; set => Bits_New = (byte)((Bits_New & ~(1u << 0)) | ((value & 1u) << 0)); }
    public uint Hit { readonly get => ((uint)Bits_New >> 1) & 1u; set => Bits_New = (byte)((Bits_New & ~(1u << 1)) | ((value & 1u) << 1)); }
    public uint Reserve { readonly get => ((uint)Bits_New >> 2) & 1u; set => Bits_New = (byte)((Bits_New & ~(1u << 2)) | ((value & 1u) << 2)); }
    public byte TimeFlag;
    public byte Time;
    public uint Point;
    public SYSTEMTIME saleStart;
    public SYSTEMTIME saleEnd;
}

/// <summary>Registros das tabelas do pangya.iff (classdefine.h, namespace IFF_STRUCT).</summary>
public static class Iff
{
    /// <summary>IFF_STRUCT::sChar (372 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 372)]
    public partial struct sChar
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public ByteArray40 HairTex;
        public ByteArray40 ShirtsTex;
        public ByteArray40 FaceTex;
        public Int16Array5 Attr;
        public byte nParts;
        public byte nAcsries;
        public byte ClubType;
        public float ClubScale;
        public ByteArray5 PCL;
        public ByteArray40 Mtn30sWinner;
    }

    /// <summary>IFF_STRUCT::sPart (516 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 516)]
    public partial struct sPart
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public byte Category;
        public uint PosMask;
        public uint HideMask;
        public ByteArray40Array3 Tex;
        public ByteArray40Array3 OrgTex;
        public Int16Array5 Attr;
        public Int16Array5 Slot;
        public ByteArray40 EquippableWith;
        public UInt32Array2 SubPart;
        public short CharacterSlot;
        public short CaddieSlot;
        public uint RentalPrice;
        public byte Beginner;
        public short Point;
    }

    /// <summary>IFF_STRUCT::sClub (196 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 196)]
    public partial struct sClub
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public byte Type;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sClubSet (180 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 180)]
    public partial struct sClubSet
    {
        public IFF_ITEM_COMMON c;
        public UInt32Array4 ClubIds;
        public Int16Array5 Attr;
        public Int16Array5 Slot;
    }

    /// <summary>IFF_STRUCT::sBall (764 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 764)]
    public partial struct sBall
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public uint Bound;
        public uint Roll;
        public ByteArray40Array7 Fx;
        public ByteArray40Array7 FxBone;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sCaddie (200 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 200)]
    public partial struct sCaddie
    {
        public IFF_ITEM_COMMON c;
        public uint MonthlyFee;
        public ByteArray40 Data;
        public Int16Array5 Attr;
    }

    /// <summary>IFF_STRUCT::sCadItem (236 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 236)]
    public partial struct sCadItem
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 FaceTex;
        public ByteArray40 BodyTex;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sSetItem (220 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 220)]
    public partial struct sSetItem
    {
        public IFF_ITEM_COMMON c;
        public byte nElems;
        public UInt32Array10 ElemIds;
        public Int16Array10 ElemNum;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sCourse (312 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 312)]
    public partial struct sCourse
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public ByteArray40 AmbientSnd;
        public byte Bits_Difficulty;
        public uint Difficulty { readonly get => ((uint)Bits_Difficulty >> 0) & 15u; set => Bits_Difficulty = (byte)((Bits_Difficulty & ~(15u << 0)) | ((value & 15u) << 0)); }
        public uint DiffFlag { readonly get => ((uint)Bits_Difficulty >> 4) & 15u; set => Bits_Difficulty = (byte)((Bits_Difficulty & ~(15u << 4)) | ((value & 15u) << 4)); }
        public ByteArray40 TexProp;
        public float Slope;
        public ByteArray40 SkyFx;
    }

    /// <summary>IFF_STRUCT::sMatch (332 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 332)]
    public partial struct sMatch
    {
        public byte Final;
        public uint TypeId;
        public ByteArray80 Name;
        public byte Level;
        public ByteArray40Array6 Icon;
    }

    /// <summary>IFF_STRUCT::sTitle (88 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 88)]
    public partial struct sTitle
    {
        public byte Final;
        public uint TypeId;
        public ByteArray40 Name;
        public ByteArray40 Icon;
    }

    /// <summary>IFF_STRUCT::sEnchant (16 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 16)]
    public partial struct sEnchant
    {
        public byte Final;
        public uint TypeId;
        public uint ReqdPang;
        public byte ReqdLevel;
    }

    /// <summary>IFF_STRUCT::sSkin (196 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 196)]
    public partial struct sSkin
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Tex;
        public byte HScroll;
        public byte VScroll;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sHairStyle (148 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 148)]
    public partial struct sHairStyle
    {
        public IFF_ITEM_COMMON c;
        public byte cHairID;
        public byte cCharID;
    }

    /// <summary>IFF_STRUCT::sChildItem (72 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 72)]
    public partial struct sChildItem
    {
        public byte Final;
        public uint TypeId;
        public ByteArray40 Name;
        public byte Bits_Level;
        public uint Level { readonly get => ((uint)Bits_Level >> 0) & 127u; set => Bits_Level = (byte)((Bits_Level & ~(127u << 0)) | ((value & 127u) << 0)); }
        public uint IsUnderLvl { readonly get => ((uint)Bits_Level >> 7) & 1u; set => Bits_Level = (byte)((Bits_Level & ~(1u << 7)) | ((value & 1u) << 7)); }
        public byte Bits_IsDisplay;
        public uint IsDisplay { readonly get => ((uint)Bits_IsDisplay >> 0) & 1u; set => Bits_IsDisplay = (byte)((Bits_IsDisplay & ~(1u << 0)) | ((value & 1u) << 0)); }
        public uint IsCash { readonly get => ((uint)Bits_IsDisplay >> 1) & 1u; set => Bits_IsDisplay = (byte)((Bits_IsDisplay & ~(1u << 1)) | ((value & 1u) << 1)); }
        public uint IsSalable { readonly get => ((uint)Bits_IsDisplay >> 2) & 1u; set => Bits_IsDisplay = (byte)((Bits_IsDisplay & ~(1u << 2)) | ((value & 1u) << 2)); }
        public uint NumberPrice;
        public byte NumberFlag;
        public ushort Number;
        public uint TimePrice;
        public byte TimeFlag;
        public ushort Time;
        public short FailPercent;
    }

    /// <summary>IFF_STRUCT::sItem (200 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 200)]
    public partial struct sItem
    {
        public IFF_ITEM_COMMON c;
        public uint Bits_RandomBox;
        public uint RandomBox { readonly get => ((uint)Bits_RandomBox >> 0) & 1u; set => Bits_RandomBox = (uint)((Bits_RandomBox & ~(1u << 0)) | ((value & 1u) << 0)); }
        public ByteArray40 Data;
        public Int16Array5 COM;
        public short Point;
    }

    /// <summary>IFF_STRUCT::sMascot (252 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 252)]
    public partial struct sMascot
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public ByteArray40 MsgTex;
        public ByteArray5 COM;
        public ByteArray5 Attr;
        public sbyte DriveUp;
        public ushort ItemDropUp;
        public ushort ComboUp;
        public ushort PangUp;
        public ushort ExpUp;
        public byte ItemSlot;
        public byte ShowMsg;
        public uint MsgFee;
    }

    /// <summary>IFF_STRUCT::sAuxPart (176 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 176)]
    public partial struct sAuxPart
    {
        public IFF_ITEM_COMMON c;
        public Int16Array5 COM;
        public ByteArray5 Attr;
        public ByteArray5 Slot;
        public sbyte DriveUp;
        public ushort ItemDropUp;
        public ushort ComboUp;
        public ushort PangUp;
        public ushort ExpUp;
    }

    /// <summary>IFF_STRUCT::sQuestDrop (244 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 244)]
    public partial struct sQuestDrop
    {
        public IFF_ITEM_COMMON c;
        public SYSTEMTIME dropStart;
        public SYSTEMTIME dropEnd;
        public ByteArray40 dropFx;
        public byte dropCycle;
        public UInt16Array10 holesToPlay;
        public byte mapDiff;
        public byte holeDrop;
        public byte timeDrop;
    }

    /// <summary>IFF_STRUCT::sCard (328 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 328)]
    public partial struct sCard
    {
        public IFF_ITEM_COMMON c;
        public byte RareType;
        public ByteArray40 Image;
        public Int16Array5 COM;
        public ushort Avility;
        public ushort AvilityValue;
        public ByteArray40 SubIcon;
        public ByteArray40 SlotImg;
        public ByteArray40 BuffImg;
        public ushort UseTime;
        public ushort Volume;
        public ushort CardIndex;
    }

    /// <summary>IFF_STRUCT::sFurniture (464 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 464)]
    public partial struct sFurniture
    {
        public IFF_ITEM_COMMON c;
        public ByteArray40 Data;
        public short Num;
        public short IsOwn;
        public short IsMove;
        public short IsFunction;
        public short Etc;
        public SingleArray4 Pos;
        public ByteArray40Array3 Tex;
        public ByteArray40Array3 OrgTex;
        public Int16Array5 COM;
        public ushort UseTime;
    }

    /// <summary>IFF_STRUCT::sOfflineShop (200 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 200)]
    public partial struct sOfflineShop
    {
        public IFF_ITEM_COMMON c;
        public byte nElems;
        public UInt32Array10 ElemIds;
        public Int16Array5 COM;
    }

    /// <summary>IFF_STRUCT::sDesc (516 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 516)]
    public partial struct sDesc
    {
        public uint TypeId;
        public ByteArray512 Desc;
    }

    /// <summary>IFF_STRUCT::sRandomBox (228 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 228)]
    public partial struct sRandomBox
    {
        public byte active;
        public ByteArray35 unknown01;
        public uint boxTypeId;
        public byte kind;
        public uint typeId;
        public UInt32Array2 unknown30;
        public uint checkTypeId;
        public UInt32Array42 unknown3C;
    }

    /// <summary>IFF_STRUCT::sRandomRecycle (16 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 16)]
    public partial struct sRandomRecycle
    {
        public uint uiRandSeq;
        public uint uiTypeId;
        public uint uiCount;
        public uint uiProbs;
    }

    /// <summary>IFF_STRUCT::sNonVisibleItem (44 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 44)]
    public partial struct sNonVisibleItem
    {
        public byte active;
        public uint type;
        public uint typeId;
        public SYSTEMTIME start;
        public SYSTEMTIME end;
    }

    /// <summary>IFF_STRUCT::sSubscriptionItem (44 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 44)]
    public partial struct sSubscriptionItem
    {
        public byte active;
        public uint type;
        public uint typeId;
        public SYSTEMTIME start;
        public SYSTEMTIME end;
    }

    /// <summary>IFF_STRUCT::sSpecialPrizeItem (12 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 12)]
    public partial struct sSpecialPrizeItem
    {
        public uint typeId;
        public uint ability;
        public float rate;
    }

    /// <summary>IFF_STRUCT::sCadieMagicBox (104 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 104)]
    public partial struct sCadieMagicBox
    {
        public uint uiNumber;
        public byte bFinal;
        public uint uiCategory;
        public int iCharacter;
        public int iLevel;
        public uint uiOutput;
        public uint uiOutputCount;
        public UInt32Array4 uiElem;
        public UInt32Array4 uiElemCount;
        public uint uiRandSeq;
        public ByteArray40 szRandName;
    }

    /// <summary>IFF_STRUCT::sFurnitureAbility (60 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 60)]
    public partial struct sFurnitureAbility
    {
        public byte bFinal;
        public byte btAbilityType;
        public uint dwFurnitureTID;
        public byte btSuccessType;
        public int iStayTime;
        public byte btEffectType;
        public uint dwSetInTID;
        public int iMaxCountAtFurniture;
        public SYSTEMTIME stStart;
        public uint dwDuringTime;
        public uint dwPutOutTID;
        public int iProbability;
        public int iMaxCountAtUser;
    }

    /// <summary>IFF_STRUCT::sTikiOutputTable (52 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 52)]
    public partial struct sTikiOutputTable
    {
        public uint uiIndex;
        public byte bFinal;
        public ByteArray32 strCategory;
        public uint uiTypeID;
        public uint uiCount;
        public uint uiRate;
    }

    /// <summary>IFF_STRUCT::sTikiPointTable (48 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 48)]
    public partial struct sTikiPointTable
    {
        public uint uiIndex;
        public byte bFinal;
        public ByteArray32 strCategory;
        public uint uiMin;
        public uint uiMax;
    }

    /// <summary>IFF_STRUCT::sTikiSpecialRecipe (60 bytes).</summary>
    [StructLayout(LayoutKind.Sequential, Pack = 8, Size = 60)]
    public partial struct sTikiSpecialRecipe
    {
        public uint uiIndex;
        public byte bFinal;
        public ByteArray32 strCategory;
        public uint uiElemCount;
        public UInt32Array4 uiElem;
    }
}

// Arrays de tamanho fixo (char[N] etc.); convertem para Span<T> implicitamente.
[InlineArray(100)] public struct ByteArray100 { byte _e; }
[InlineArray(101)] public struct ByteArray101 { byte _e; }
[InlineArray(1024)] public struct ByteArray1024 { byte _e; }
[InlineArray(11)] public struct ByteArray11 { byte _e; }
[InlineArray(110)] public struct ByteArray110 { byte _e; }
[InlineArray(12)] public struct ByteArray12 { byte _e; }
[InlineArray(128)] public struct ByteArray128 { byte _e; }
[InlineArray(2)] public struct ByteArray12Array2 { ByteArray12 _e; }
[InlineArray(16)] public struct ByteArray16 { byte _e; }
[InlineArray(18)] public struct ByteArray18 { byte _e; }
[InlineArray(2)] public struct ByteArray2 { byte _e; }
[InlineArray(20)] public struct ByteArray20 { byte _e; }
[InlineArray(21)] public struct ByteArray21 { byte _e; }
[InlineArray(2)] public struct ByteArray21Array2 { ByteArray21 _e; }
[InlineArray(22)] public struct ByteArray22 { byte _e; }
[InlineArray(25)] public struct ByteArray25 { byte _e; }
[InlineArray(3)] public struct ByteArray3 { byte _e; }
[InlineArray(30)] public struct ByteArray30 { byte _e; }
[InlineArray(32)] public struct ByteArray32 { byte _e; }
[InlineArray(35)] public struct ByteArray35 { byte _e; }
[InlineArray(4)] public struct ByteArray4 { byte _e; }
[InlineArray(40)] public struct ByteArray40 { byte _e; }
[InlineArray(3)] public struct ByteArray40Array3 { ByteArray40 _e; }
[InlineArray(6)] public struct ByteArray40Array6 { ByteArray40 _e; }
[InlineArray(7)] public struct ByteArray40Array7 { ByteArray40 _e; }
[InlineArray(41)] public struct ByteArray41 { byte _e; }
[InlineArray(46)] public struct ByteArray46 { byte _e; }
[InlineArray(5)] public struct ByteArray5 { byte _e; }
[InlineArray(512)] public struct ByteArray512 { byte _e; }
[InlineArray(53)] public struct ByteArray53 { byte _e; }
[InlineArray(6)] public struct ByteArray6 { byte _e; }
[InlineArray(64)] public struct ByteArray64 { byte _e; }
[InlineArray(80)] public struct ByteArray80 { byte _e; }
[InlineArray(9)] public struct ByteArray9 { byte _e; }
[InlineArray(24)] public struct ByteArray9Array24 { ByteArray9 _e; }
[InlineArray(10)] public struct Int16Array10 { short _e; }
[InlineArray(5)] public struct Int16Array5 { short _e; }
[InlineArray(6)] public struct Int64Array6 { long _e; }
[InlineArray(3)] public struct SingleArray3 { float _e; }
[InlineArray(4)] public struct SingleArray4 { float _e; }
[InlineArray(10)] public struct UInt16Array10 { ushort _e; }
[InlineArray(3)] public struct UInt16Array3 { ushort _e; }
[InlineArray(13)] public struct UInt16Array3Array13 { UInt16Array3 _e; }
[InlineArray(10)] public struct UInt32Array10 { uint _e; }
[InlineArray(12)] public struct UInt32Array12 { uint _e; }
[InlineArray(2)] public struct UInt32Array2 { uint _e; }
[InlineArray(24)] public struct UInt32Array24 { uint _e; }
[InlineArray(3)] public struct UInt32Array3 { uint _e; }
[InlineArray(4)] public struct UInt32Array4 { uint _e; }
[InlineArray(42)] public struct UInt32Array42 { uint _e; }
[InlineArray(3)] public struct UInt32Array4Array3 { UInt32Array4 _e; }
[InlineArray(5)] public struct UInt32Array5 { uint _e; }
[InlineArray(6)] public struct UInt32Array6 { uint _e; }
[InlineArray(20)] public struct sMapStatisticsArray20 { sMapStatistics _e; }
[InlineArray(12)] public struct sStallSlotArray12 { sStallSlot _e; }
