// <auto-generated> Gerado por tools/StructGen. Confere tamanho e offset de cada campo contra o layout do clang (MSVC x86). </auto-generated>
using System.Runtime.CompilerServices;
using Pangya.Protocol.KR645;

namespace Pangya.Tests;

public partial class StructLayoutTests
{
    static int Off<T, F>(ref T s, ref F f) => (int)Unsafe.ByteOffset(ref Unsafe.As<T, byte>(ref s), ref Unsafe.As<F, byte>(ref f));
    [Fact] public void SYSTEMTIME()
    {
        Assert.Equal(16, Unsafe.SizeOf<SYSTEMTIME>());
        var s = new SYSTEMTIME();
        Assert.Equal(0, Off(ref s, ref s.wYear));
        Assert.Equal(2, Off(ref s, ref s.wMonth));
        Assert.Equal(4, Off(ref s, ref s.wDayOfWeek));
        Assert.Equal(6, Off(ref s, ref s.wDay));
        Assert.Equal(8, Off(ref s, ref s.wHour));
        Assert.Equal(10, Off(ref s, ref s.wMinute));
        Assert.Equal(12, Off(ref s, ref s.wSecond));
        Assert.Equal(14, Off(ref s, ref s.wMilliseconds));
    }
    [Fact] public void sRoomDetail()
    {
        Assert.Equal(12, Unsafe.SizeOf<sRoomDetail>());
        var s = new sRoomDetail();
        Assert.Equal(0, Off(ref s, ref s.holes));
        Assert.Equal(1, Off(ref s, ref s.gameTime));
        Assert.Equal(5, Off(ref s, ref s.map));
        Assert.Equal(6, Off(ref s, ref s.gameType));
        Assert.Equal(7, Off(ref s, ref s.holeOrder));
        Assert.Equal(8, Off(ref s, ref s.matchTypeId));
    }
    [Fact] public void sPangYaUserInfo()
    {
        Assert.Equal(269, Unsafe.SizeOf<sPangYaUserInfo>());
        var s = new sPangYaUserInfo();
        Assert.Equal(0, Off(ref s, ref s.sID));
        Assert.Equal(22, Off(ref s, ref s.sNick));
        Assert.Equal(44, Off(ref s, ref s.sGuild));
        Assert.Equal(65, Off(ref s, ref s.szEmblemName));
        Assert.Equal(77, Off(ref s, ref s.school));
        Assert.Equal(81, Off(ref s, ref s.dwIdentity));
        Assert.Equal(85, Off(ref s, ref s.dwGalleryGuid));
        Assert.Equal(89, Off(ref s, ref s.dwGuid));
        Assert.Equal(93, Off(ref s, ref s.dwRank));
        Assert.Equal(105, Off(ref s, ref s.dwGuildId));
        Assert.Equal(109, Off(ref s, ref s.dwEmblemVer));
        Assert.Equal(113, Off(ref s, ref s.Bits_DoTutorial));
        Assert.Equal(114, Off(ref s, ref s.Bits_NewYearEvent));
        Assert.Equal(115, Off(ref s, ref s.iBongdariShopUsableTimes));
        Assert.Equal(117, Off(ref s, ref s.iBongdariShopBonusTimes));
        Assert.Equal(119, Off(ref s, ref s.iBongdariShopRemainedBonus));
        Assert.Equal(121, Off(ref s, ref s.dwPointPointEvent));
        Assert.Equal(125, Off(ref s, ref s.dwFlagBlock));
        Assert.Equal(129, Off(ref s, ref s.iTimeBlock));
        Assert.Equal(133, Off(ref s, ref s.nChannelingFlag));
        Assert.Equal(137, Off(ref s, ref s.sDisplayID));
        Assert.Equal(265, Off(ref s, ref s.dwUID));
    }
    [Fact] public void sPangYaUserStatistics()
    {
        Assert.Equal(235, Unsafe.SizeOf<sPangYaUserStatistics>());
        var s = new sPangYaUserStatistics();
        Assert.Equal(0, Off(ref s, ref s.dwDrive));
        Assert.Equal(4, Off(ref s, ref s.dwPutt));
        Assert.Equal(8, Off(ref s, ref s.dwVisitTime));
        Assert.Equal(12, Off(ref s, ref s.dwShotTime));
        Assert.Equal(16, Off(ref s, ref s.fLongest));
        Assert.Equal(20, Off(ref s, ref s.dwPangya));
        Assert.Equal(24, Off(ref s, ref s.dwTimeOut));
        Assert.Equal(28, Off(ref s, ref s.dwOB));
        Assert.Equal(32, Off(ref s, ref s.dwDistance));
        Assert.Equal(36, Off(ref s, ref s.dwHole));
        Assert.Equal(40, Off(ref s, ref s.dwMatchHole));
        Assert.Equal(44, Off(ref s, ref s.wHoleInOne));
        Assert.Equal(46, Off(ref s, ref s.wBunker));
        Assert.Equal(48, Off(ref s, ref s.dwFairway));
        Assert.Equal(52, Off(ref s, ref s.wAlbatross));
        Assert.Equal(54, Off(ref s, ref s.dwHoleIn));
        Assert.Equal(58, Off(ref s, ref s.dwPuttIn));
        Assert.Equal(62, Off(ref s, ref s.fLongestPuttIn));
        Assert.Equal(66, Off(ref s, ref s.fLongestChipIn));
        Assert.Equal(70, Off(ref s, ref s.dwExp));
        Assert.Equal(74, Off(ref s, ref s.Level));
        Assert.Equal(75, Off(ref s, ref s.i64Pang));
        Assert.Equal(83, Off(ref s, ref s.iTotalScore));
        Assert.Equal(87, Off(ref s, ref s.cBestScore));
        Assert.Equal(93, Off(ref s, ref s.i64MaxPang));
        Assert.Equal(141, Off(ref s, ref s.dwGameCount));
        Assert.Equal(145, Off(ref s, ref s.dwDisconnectCount));
        Assert.Equal(149, Off(ref s, ref s.dwTeamWin));
        Assert.Equal(153, Off(ref s, ref s.dwTeamGames));
        Assert.Equal(157, Off(ref s, ref s.dwLadderPoint));
        Assert.Equal(161, Off(ref s, ref s.dwLadderWin));
        Assert.Equal(165, Off(ref s, ref s.dwLadderLose));
        Assert.Equal(169, Off(ref s, ref s.dwLadderDraw));
        Assert.Equal(173, Off(ref s, ref s.dwLadderHoles));
        Assert.Equal(177, Off(ref s, ref s.nMannerCombo));
        Assert.Equal(181, Off(ref s, ref s.nMaxMannerCombo));
        Assert.Equal(185, Off(ref s, ref s.dwNoMannerGameCount));
        Assert.Equal(189, Off(ref s, ref s.i64TotalSkinsPang));
        Assert.Equal(197, Off(ref s, ref s.dwSkinsWin));
        Assert.Equal(201, Off(ref s, ref s.dwSkinsLose));
        Assert.Equal(205, Off(ref s, ref s.dwSkinsGames));
        Assert.Equal(209, Off(ref s, ref s.iStrikePoint));
        Assert.Equal(213, Off(ref s, ref s.iAllInCount));
        Assert.Equal(215, Off(ref s, ref s.eventValue));
        Assert.Equal(219, Off(ref s, ref s.eventFlag));
        Assert.Equal(223, Off(ref s, ref s.dwSeasonCount));
        Assert.Equal(227, Off(ref s, ref s.i64SumPang));
    }
    [Fact] public void sTrophyStatistics()
    {
        Assert.Equal(78, Unsafe.SizeOf<sTrophyStatistics>());
        var s = new sTrophyStatistics();
        Assert.Equal(0, Off(ref s, ref s.Trophy));
    }
    [Fact] public void sUserEquip()
    {
        Assert.Equal(108, Unsafe.SizeOf<sUserEquip>());
        var s = new sUserEquip();
        Assert.Equal(0, Off(ref s, ref s.guidCaddie));
        Assert.Equal(4, Off(ref s, ref s.guidChar));
        Assert.Equal(8, Off(ref s, ref s.guidClubSet));
        Assert.Equal(12, Off(ref s, ref s.tidBall));
        Assert.Equal(16, Off(ref s, ref s.tidItemSlot));
        Assert.Equal(56, Off(ref s, ref s.guidSkin));
        Assert.Equal(80, Off(ref s, ref s.tidSkin));
        Assert.Equal(104, Off(ref s, ref s.guidMascot));
    }
    [Fact] public void sMapStatistics()
    {
        Assert.Equal(43, Unsafe.SizeOf<sMapStatistics>());
        var s = new sMapStatistics();
        Assert.Equal(0, Off(ref s, ref s.bMap));
        Assert.Equal(1, Off(ref s, ref s.dwDrive));
        Assert.Equal(5, Off(ref s, ref s.dwPutt));
        Assert.Equal(9, Off(ref s, ref s.dwHole));
        Assert.Equal(13, Off(ref s, ref s.dwFairway));
        Assert.Equal(17, Off(ref s, ref s.dwHoleIn));
        Assert.Equal(21, Off(ref s, ref s.dwPuttIn));
        Assert.Equal(25, Off(ref s, ref s.iTotalScore));
        Assert.Equal(29, Off(ref s, ref s.cBestScore));
        Assert.Equal(30, Off(ref s, ref s.i64MaxPang));
        Assert.Equal(38, Off(ref s, ref s.tidChar));
        Assert.Equal(42, Off(ref s, ref s.eventScore));
    }
    [Fact] public void sMyInfo()
    {
        Assert.Equal(2412, Unsafe.SizeOf<sMyInfo>());
        var s = new sMyInfo();
        Assert.Equal(0, Off(ref s, ref s.roomIndex));
        Assert.Equal(2, Off(ref s, ref s.info));
        Assert.Equal(271, Off(ref s, ref s.stat));
        Assert.Equal(506, Off(ref s, ref s.trophy));
        Assert.Equal(584, Off(ref s, ref s.userEquip));
        Assert.Equal(692, Off(ref s, ref s.mapStat));
        Assert.Equal(1552, Off(ref s, ref s.classicMapStat));
    }
    [Fact] public void sCharacterInfo()
    {
        Assert.Equal(444, Unsafe.SizeOf<sCharacterInfo>());
        var s = new sCharacterInfo();
        Assert.Equal(0, Off(ref s, ref s.tid));
        Assert.Equal(4, Off(ref s, ref s.guid));
        Assert.Equal(8, Off(ref s, ref s.tidParts));
        Assert.Equal(104, Off(ref s, ref s.hairClr));
        Assert.Equal(105, Off(ref s, ref s.Bits_shirtsClr));
        Assert.Equal(106, Off(ref s, ref s.PCL));
        Assert.Equal(111, Off(ref s, ref s.Purchase));
        Assert.Equal(112, Off(ref s, ref s.tidAuxParts));
        Assert.Equal(132, Off(ref s, ref s.UccIndexList));
        Assert.Equal(348, Off(ref s, ref s.ItemIdList));
    }
    [Fact] public void sCaddieInfo()
    {
        Assert.Equal(25, Unsafe.SizeOf<sCaddieInfo>());
        var s = new sCaddieInfo();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.tidPart));
        Assert.Equal(12, Off(ref s, ref s.Level));
        Assert.Equal(13, Off(ref s, ref s.Exp));
        Assert.Equal(17, Off(ref s, ref s.Bits_gift_flag));
        Assert.Equal(18, Off(ref s, ref s.Remain_Date));
        Assert.Equal(20, Off(ref s, ref s.Remain_Partdate));
        Assert.Equal(22, Off(ref s, ref s.Purchase));
        Assert.Equal(23, Off(ref s, ref s.byCheckCaddieWarning));
        Assert.Equal(24, Off(ref s, ref s.PCBangCaddie));
    }
    [Fact] public void sClubInfo()
    {
        Assert.Equal(18, Unsafe.SizeOf<sClubInfo>());
        var s = new sClubInfo();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.PCL));
    }
    [Fact] public void sMascotInfo()
    {
        Assert.Equal(63, Unsafe.SizeOf<sMascotInfo>());
        var s = new sMascotInfo();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.Level));
        Assert.Equal(9, Off(ref s, ref s.Exp));
        Assert.Equal(13, Off(ref s, ref s.szMsg));
        Assert.Equal(43, Off(ref s, ref s.Remain_Date));
        Assert.Equal(45, Off(ref s, ref s.Purchase));
        Assert.Equal(46, Off(ref s, ref s.endDate));
        Assert.Equal(62, Off(ref s, ref s.PCBangMascot));
    }
    [Fact] public void sUserInfo()
    {
        Assert.Equal(2962, Unsafe.SizeOf<sUserInfo>());
        var s = new sUserInfo();
        Assert.Equal(0, Off(ref s, ref s.roomIndex));
        Assert.Equal(2, Off(ref s, ref s.info));
        Assert.Equal(271, Off(ref s, ref s.stat));
        Assert.Equal(506, Off(ref s, ref s.trophy));
        Assert.Equal(584, Off(ref s, ref s.userEquip));
        Assert.Equal(692, Off(ref s, ref s.mapStat));
        Assert.Equal(1552, Off(ref s, ref s.classicMapStat));
        Assert.Equal(2412, Off(ref s, ref s.charInfo));
        Assert.Equal(2856, Off(ref s, ref s.caddieInfo));
        Assert.Equal(2881, Off(ref s, ref s.clubInfo));
        Assert.Equal(2899, Off(ref s, ref s.mascotInfo));
    }
    [Fact] public void sSpecialTrophy()
    {
        Assert.Equal(12, Unsafe.SizeOf<sSpecialTrophy>());
        var s = new sSpecialTrophy();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.count));
    }
    [Fact] public void sGuildTrophy()
    {
        Assert.Equal(4, Unsafe.SizeOf<sGuildTrophy>());
        var s = new sGuildTrophy();
        Assert.Equal(0, Off(ref s, ref s.TypeID));
    }
    [Fact] public void sUserPosition()
    {
        Assert.Equal(75, Unsafe.SizeOf<sUserPosition>());
        var s = new sUserPosition();
        Assert.Equal(0, Off(ref s, ref s.iRoomIdx));
        Assert.Equal(2, Off(ref s, ref s.iRoomType));
        Assert.Equal(6, Off(ref s, ref s.iServerGUID));
        Assert.Equal(10, Off(ref s, ref s.iChannelUid));
        Assert.Equal(11, Off(ref s, ref s.csChannelName));
    }
    [Fact] public void sItemInfo()
    {
        Assert.Equal(168, Unsafe.SizeOf<sItemInfo>());
        var s = new sItemInfo();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.HourRemain));
        Assert.Equal(12, Off(ref s, ref s.Common));
        Assert.Equal(22, Off(ref s, ref s.Purchase));
        Assert.Equal(23, Off(ref s, ref s.Bits_gift_flag));
        Assert.Equal(24, Off(ref s, ref s.ItemDate));
        Assert.Equal(40, Off(ref s, ref s.Bits_Reserve));
        Assert.Equal(41, Off(ref s, ref s.ItemName));
        Assert.Equal(82, Off(ref s, ref s.UccIndex));
        Assert.Equal(91, Off(ref s, ref s.status));
        Assert.Equal(92, Off(ref s, ref s.Seq));
        Assert.Equal(94, Off(ref s, ref s.CopierNick));
        Assert.Equal(116, Off(ref s, ref s.attachCard));
        Assert.Equal(164, Off(ref s, ref s.CharacterSlotNum));
        Assert.Equal(166, Off(ref s, ref s.CaddieSlotNum));
    }
    [Fact] public void GUILD_HISTORY()
    {
        Assert.Equal(49, Unsafe.SizeOf<GUILD_HISTORY>());
        var s = new GUILD_HISTORY();
        Assert.Equal(0, Off(ref s, ref s.index));
        Assert.Equal(4, Off(ref s, ref s.guildUID));
        Assert.Equal(8, Off(ref s, ref s.guildName));
        Assert.Equal(29, Off(ref s, ref s.state));
        Assert.Equal(33, Off(ref s, ref s.time));
    }
    [Fact] public void GUILD_USER_INFO()
    {
        Assert.Equal(281, Unsafe.SizeOf<GUILD_USER_INFO>());
        var s = new GUILD_USER_INFO();
        Assert.Equal(0, Off(ref s, ref s.guildUID));
        Assert.Equal(4, Off(ref s, ref s.guildName));
        Assert.Equal(25, Off(ref s, ref s.guildPang));
        Assert.Equal(29, Off(ref s, ref s.guildPoint));
        Assert.Equal(33, Off(ref s, ref s.memberCount));
        Assert.Equal(37, Off(ref s, ref s.guildMark));
        Assert.Equal(49, Off(ref s, ref s.notice));
        Assert.Equal(150, Off(ref s, ref s.introduce));
        Assert.Equal(251, Off(ref s, ref s.classIdx));
        Assert.Equal(255, Off(ref s, ref s.masterUID));
        Assert.Equal(259, Off(ref s, ref s.masterNickname));
    }
    [Fact] public void GUILD_INFO()
    {
        Assert.Equal(297, Unsafe.SizeOf<GUILD_INFO>());
        var s = new GUILD_INFO();
        Assert.Equal(0, Off(ref s, ref s.guildUID));
        Assert.Equal(4, Off(ref s, ref s.guildName));
        Assert.Equal(25, Off(ref s, ref s.guildPang));
        Assert.Equal(29, Off(ref s, ref s.guildPoint));
        Assert.Equal(33, Off(ref s, ref s.memberCount));
        Assert.Equal(37, Off(ref s, ref s.guildMark));
        Assert.Equal(49, Off(ref s, ref s.notice));
        Assert.Equal(150, Off(ref s, ref s.introduce));
        Assert.Equal(251, Off(ref s, ref s.classIdx));
        Assert.Equal(255, Off(ref s, ref s.masterUID));
        Assert.Equal(259, Off(ref s, ref s.masterNickname));
        Assert.Equal(281, Off(ref s, ref s.createTime));
    }
    [Fact] public void GUILD_LIST()
    {
        Assert.Equal(196, Unsafe.SizeOf<GUILD_LIST>());
        var s = new GUILD_LIST();
        Assert.Equal(0, Off(ref s, ref s.guildUID));
        Assert.Equal(4, Off(ref s, ref s.guildName));
        Assert.Equal(25, Off(ref s, ref s.guildPang));
        Assert.Equal(29, Off(ref s, ref s.guildPoint));
        Assert.Equal(33, Off(ref s, ref s.memberCount));
        Assert.Equal(37, Off(ref s, ref s.createTime));
        Assert.Equal(53, Off(ref s, ref s.introduce));
        Assert.Equal(154, Off(ref s, ref s.unknown9a));
        Assert.Equal(158, Off(ref s, ref s.masterUID));
        Assert.Equal(162, Off(ref s, ref s.masterNickname));
        Assert.Equal(184, Off(ref s, ref s.guildMark));
    }
    [Fact] public void GUILD_USER_LIST()
    {
        Assert.Equal(81, Unsafe.SizeOf<GUILD_USER_LIST>());
        var s = new GUILD_USER_LIST();
        Assert.Equal(0, Off(ref s, ref s.guildUID));
        Assert.Equal(4, Off(ref s, ref s.userUID));
        Assert.Equal(8, Off(ref s, ref s.classIdx));
        Assert.Equal(12, Off(ref s, ref s.message));
        Assert.Equal(37, Off(ref s, ref s.guildName));
        Assert.Equal(58, Off(ref s, ref s.nickname));
        Assert.Equal(80, Off(ref s, ref s.online));
    }
    [Fact] public void GUILD_USER_MSN_LIST()
    {
        Assert.Equal(55, Unsafe.SizeOf<GUILD_USER_MSN_LIST>());
        var s = new GUILD_USER_MSN_LIST();
        Assert.Equal(0, Off(ref s, ref s.userUID));
        Assert.Equal(4, Off(ref s, ref s.guildUID));
        Assert.Equal(8, Off(ref s, ref s.sex));
        Assert.Equal(9, Off(ref s, ref s.userID));
        Assert.Equal(31, Off(ref s, ref s.nickname));
        Assert.Equal(53, Off(ref s, ref s.unknown35));
        Assert.Equal(54, Off(ref s, ref s.online));
    }
    [Fact] public void sTreasureHunt()
    {
        Assert.Equal(11, Unsafe.SizeOf<sTreasureHunt>());
        var s = new sTreasureHunt();
        Assert.Equal(0, Off(ref s, ref s.dwUID));
        Assert.Equal(4, Off(ref s, ref s.dwTid));
        Assert.Equal(8, Off(ref s, ref s.wCount));
        Assert.Equal(10, Off(ref s, ref s.byItemType));
    }
    [Fact] public void sTreasureGift()
    {
        Assert.Equal(21, Unsafe.SizeOf<sTreasureGift>());
        var s = new sTreasureGift();
        Assert.Equal(0, Off(ref s, ref s.dwUID));
        Assert.Equal(4, Off(ref s, ref s.dwTid));
        Assert.Equal(8, Off(ref s, ref s.dwItemGuid));
        Assert.Equal(12, Off(ref s, ref s.wCount));
        Assert.Equal(14, Off(ref s, ref s.byItemType));
        Assert.Equal(15, Off(ref s, ref s.iHourRemain));
        Assert.Equal(19, Off(ref s, ref s.reserved));
    }
    [Fact] public void sTreasureItem()
    {
        Assert.Equal(5, Unsafe.SizeOf<sTreasureItem>());
        var s = new sTreasureItem();
        Assert.Equal(0, Off(ref s, ref s.byMapIndex));
        Assert.Equal(1, Off(ref s, ref s.dwGauge));
    }
    [Fact] public void stGameClass()
    {
        Assert.Equal(8, Unsafe.SizeOf<stGameClass>());
        var s = new stGameClass();
        Assert.Equal(0, Off(ref s, ref s.style));
        Assert.Equal(4, Off(ref s, ref s.gameType));
    }
    [Fact] public void EncryptKey()
    {
        Assert.Equal(16, Unsafe.SizeOf<EncryptKey>());
        var s = new EncryptKey();
        Assert.Equal(0, Off(ref s, ref s.m_byKey));
    }
    [Fact] public void sUserInfoExt()
    {
        Assert.Equal(3986, Unsafe.SizeOf<sUserInfoExt>());
        var s = new sUserInfoExt();
        Assert.Equal(0, Off(ref s, ref s.roomIndex));
        Assert.Equal(2, Off(ref s, ref s.info));
        Assert.Equal(271, Off(ref s, ref s.stat));
        Assert.Equal(506, Off(ref s, ref s.trophy));
        Assert.Equal(584, Off(ref s, ref s.userEquip));
        Assert.Equal(692, Off(ref s, ref s.mapStat));
        Assert.Equal(1552, Off(ref s, ref s.classicMapStat));
        Assert.Equal(2412, Off(ref s, ref s.charInfo));
        Assert.Equal(2856, Off(ref s, ref s.caddieInfo));
        Assert.Equal(2881, Off(ref s, ref s.clubInfo));
        Assert.Equal(2899, Off(ref s, ref s.mascotInfo));
        Assert.Equal(2962, Off(ref s, ref s.ext));
    }
    [Fact] public void sUserMatchHistory()
    {
        Assert.Equal(52, Unsafe.SizeOf<sUserMatchHistory>());
        var s = new sUserMatchHistory();
        Assert.Equal(0, Off(ref s, ref s.nGender));
        Assert.Equal(4, Off(ref s, ref s.szNickName));
        Assert.Equal(26, Off(ref s, ref s.szLoginID));
        Assert.Equal(48, Off(ref s, ref s.dwUID));
    }
    [Fact] public void sLevelUpDone()
    {
        Assert.Equal(3, Unsafe.SizeOf<sLevelUpDone>());
        var s = new sLevelUpDone();
        Assert.Equal(0, Off(ref s, ref s.bDone));
        Assert.Equal(1, Off(ref s, ref s.bLevel));
        Assert.Equal(2, Off(ref s, ref s.bItemType));
    }
    [Fact] public void sBriefUserInfo()
    {
        Assert.Equal(196, Unsafe.SizeOf<sBriefUserInfo>());
        var s = new sBriefUserInfo();
        Assert.Equal(0, Off(ref s, ref s.dwUid));
        Assert.Equal(4, Off(ref s, ref s.dwGuid));
        Assert.Equal(8, Off(ref s, ref s.roomIndex));
        Assert.Equal(10, Off(ref s, ref s.sNick));
        Assert.Equal(32, Off(ref s, ref s.level));
        Assert.Equal(33, Off(ref s, ref s.dwIdentity));
        Assert.Equal(37, Off(ref s, ref s.dwTitle));
        Assert.Equal(41, Off(ref s, ref s.dwLadderPoint));
        Assert.Equal(45, Off(ref s, ref s.Bits_bSleep));
        Assert.Equal(46, Off(ref s, ref s.m_GuildId));
        Assert.Equal(50, Off(ref s, ref s.szEmblemName));
        Assert.Equal(62, Off(ref s, ref s.state));
        Assert.Equal(64, Off(ref s, ref s.nChannelingFlag));
        Assert.Equal(68, Off(ref s, ref s.reserved));
    }
    [Fact] public void sGuildRoomInfo()
    {
        Assert.Equal(74, Unsafe.SizeOf<sGuildRoomInfo>());
        var s = new sGuildRoomInfo();
        Assert.Equal(0, Off(ref s, ref s.nGuildID));
        Assert.Equal(8, Off(ref s, ref s.szName));
        Assert.Equal(50, Off(ref s, ref s.szEmblemName));
    }
    [Fact] public void sRoomInfo()
    {
        Assert.Equal(178, Unsafe.SizeOf<sRoomInfo>());
        var s = new sRoomInfo();
        Assert.Equal(0, Off(ref s, ref s.title));
        Assert.Equal(32, Off(ref s, ref s.password));
        Assert.Equal(48, Off(ref s, ref s.bPublic));
        Assert.Equal(49, Off(ref s, ref s.bAvailable));
        Assert.Equal(50, Off(ref s, ref s.bIntrusion));
        Assert.Equal(51, Off(ref s, ref s.nUserLimit));
        Assert.Equal(52, Off(ref s, ref s.nUserNum));
        Assert.Equal(53, Off(ref s, ref s.RoomKey));
        Assert.Equal(69, Off(ref s, ref s.nGalleryNum));
        Assert.Equal(70, Off(ref s, ref s.nGalleryLimit));
        Assert.Equal(71, Off(ref s, ref s.nHole));
        Assert.Equal(72, Off(ref s, ref s.gameType));
        Assert.Equal(73, Off(ref s, ref s.roomGuid));
        Assert.Equal(75, Off(ref s, ref s.holeType));
        Assert.Equal(76, Off(ref s, ref s.mapType));
        Assert.Equal(77, Off(ref s, ref s.shotTimeLimit));
        Assert.Equal(81, Off(ref s, ref s.gameTimeLimit));
        Assert.Equal(85, Off(ref s, ref s.tidMatch));
        Assert.Equal(89, Off(ref s, ref s.bSleep));
        Assert.Equal(90, Off(ref s, ref s.bAdminMaster));
        Assert.Equal(91, Off(ref s, ref s.GuildInfo));
        Assert.Equal(165, Off(ref s, ref s.pangMultiply));
        Assert.Equal(169, Off(ref s, ref s.expMultiply));
        Assert.Equal(173, Off(ref s, ref s.masterUID));
        Assert.Equal(177, Off(ref s, ref s.realGameType));
    }
    [Fact] public void sSlotInfo()
    {
        Assert.Equal(338, Unsafe.SizeOf<sSlotInfo>());
        var s = new sSlotInfo();
        Assert.Equal(0, Off(ref s, ref s.dwGuid));
        Assert.Equal(4, Off(ref s, ref s.sNick));
        Assert.Equal(26, Off(ref s, ref s.sGuild));
        Assert.Equal(47, Off(ref s, ref s.connectionRank));
        Assert.Equal(48, Off(ref s, ref s.dwIdentity));
        Assert.Equal(52, Off(ref s, ref s.dwTitle));
        Assert.Equal(56, Off(ref s, ref s.tidChar));
        Assert.Equal(60, Off(ref s, ref s.tidSkin));
        Assert.Equal(84, Off(ref s, ref s.Bits_bTeam));
        Assert.Equal(85, Off(ref s, ref s.Bits_manner));
        Assert.Equal(86, Off(ref s, ref s.level));
        Assert.Equal(87, Off(ref s, ref s.Bits_angelicWings));
        Assert.Equal(88, Off(ref s, ref s.ladderGrade));
        Assert.Equal(89, Off(ref s, ref s.GuildId));
        Assert.Equal(93, Off(ref s, ref s.szEmblemName));
        Assert.Equal(105, Off(ref s, ref s.dwUserUID));
        Assert.Equal(109, Off(ref s, ref s.state));
        Assert.Equal(113, Off(ref s, ref s.subRoomIndex));
        Assert.Equal(115, Off(ref s, ref s.action));
        Assert.Equal(119, Off(ref s, ref s.location));
        Assert.Equal(131, Off(ref s, ref s.iStateTrade));
        Assert.Equal(135, Off(ref s, ref s.strTradeTitle));
        Assert.Equal(199, Off(ref s, ref s.tidMascot));
        Assert.Equal(203, Off(ref s, ref s.pangma));
        Assert.Equal(205, Off(ref s, ref s.nChannelingFlag));
        Assert.Equal(209, Off(ref s, ref s.sDisplayID));
        Assert.Equal(337, Off(ref s, ref s.Bits_IsInvite));
    }
    [Fact] public void sChannelInfo()
    {
        Assert.Equal(77, Unsafe.SizeOf<sChannelInfo>());
        var s = new sChannelInfo();
        Assert.Equal(0, Off(ref s, ref s.Name));
        Assert.Equal(64, Off(ref s, ref s.Max_Num));
        Assert.Equal(66, Off(ref s, ref s.Current_Num));
        Assert.Equal(68, Off(ref s, ref s.Uid));
        Assert.Equal(69, Off(ref s, ref s.Type));
        Assert.Equal(73, Off(ref s, ref s.Property));
    }
    [Fact] public void sGameServerInfo()
    {
        Assert.Equal(92, Unsafe.SizeOf<sGameServerInfo>());
        var s = new sGameServerInfo();
        Assert.Equal(0, Off(ref s, ref s.name));
        Assert.Equal(40, Off(ref s, ref s.id));
        Assert.Equal(44, Off(ref s, ref s.maxUser));
        Assert.Equal(48, Off(ref s, ref s.curUser));
        Assert.Equal(52, Off(ref s, ref s.addr));
        Assert.Equal(70, Off(ref s, ref s.port));
        Assert.Equal(74, Off(ref s, ref s.property));
        Assert.Equal(78, Off(ref s, ref s.angelicWingsNum));
        Assert.Equal(82, Off(ref s, ref s.eventFlags));
        Assert.Equal(86, Off(ref s, ref s.eventValue));
        Assert.Equal(90, Off(ref s, ref s.iconIndex));
    }
    [Fact] public void sFriend()
    {
        Assert.Equal(141, Unsafe.SizeOf<sFriend>());
        var s = new sFriend();
        Assert.Equal(0, Off(ref s, ref s.NickName));
        Assert.Equal(22, Off(ref s, ref s.szAlias));
        Assert.Equal(33, Off(ref s, ref s.Uid));
        Assert.Equal(37, Off(ref s, ref s.Guid));
        Assert.Equal(41, Off(ref s, ref s.Server));
        Assert.Equal(45, Off(ref s, ref s.dwGuildId));
        Assert.Equal(49, Off(ref s, ref s.szEmblemName));
        Assert.Equal(61, Off(ref s, ref s.userPosition));
        Assert.Equal(136, Off(ref s, ref s.State));
        Assert.Equal(137, Off(ref s, ref s.Channel));
        Assert.Equal(138, Off(ref s, ref s.GameLevel));
        Assert.Equal(139, Off(ref s, ref s.Bits_Gender));
        Assert.Equal(140, Off(ref s, ref s.Bits_PangyaFriend));
    }
    [Fact] public void sNoteInfo()
    {
        Assert.Equal(109, Unsafe.SizeOf<sNoteInfo>());
        var s = new sNoteInfo();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.reserved));
        Assert.Equal(6, Off(ref s, ref s.sNick));
        Assert.Equal(28, Off(ref s, ref s.sNote));
        Assert.Equal(92, Off(ref s, ref s.sTime));
        Assert.Equal(108, Off(ref s, ref s.bReply));
    }
    [Fact] public void sMailIncludeItem()
    {
        Assert.Equal(53, Unsafe.SizeOf<sMailIncludeItem>());
        var s = new sMailIncludeItem();
        Assert.Equal(0, Off(ref s, ref s.dwIDX));
        Assert.Equal(4, Off(ref s, ref s.dwTID));
        Assert.Equal(8, Off(ref s, ref s.btItemType));
        Assert.Equal(9, Off(ref s, ref s.iCount));
        Assert.Equal(13, Off(ref s, ref s.iTimeCount));
        Assert.Equal(17, Off(ref s, ref s.soCom));
        Assert.Equal(27, Off(ref s, ref s.CharacterSlotNum));
        Assert.Equal(29, Off(ref s, ref s.CaddieSlotNum));
        Assert.Equal(31, Off(ref s, ref s.dwSetTID));
        Assert.Equal(35, Off(ref s, ref s.iSetItemCount));
        Assert.Equal(39, Off(ref s, ref s.csUCCIndex));
        Assert.Equal(48, Off(ref s, ref s.reserved30));
        Assert.Equal(52, Off(ref s, ref s.reserved34));
    }
    [Fact] public void sMailInfoBrief()
    {
        Assert.Equal(194, Unsafe.SizeOf<sMailInfoBrief>());
        var s = new sMailInfoBrief();
        Assert.Equal(0, Off(ref s, ref s.id));
        Assert.Equal(4, Off(ref s, ref s.sender));
        Assert.Equal(26, Off(ref s, ref s.reserved));
        Assert.Equal(136, Off(ref s, ref s.bRead));
        Assert.Equal(137, Off(ref s, ref s.itemCount));
        Assert.Equal(141, Off(ref s, ref s.item));
    }
    [Fact] public void sGiftInfo()
    {
        Assert.Equal(251, Unsafe.SizeOf<sGiftInfo>());
        var s = new sGiftInfo();
        Assert.Equal(0, Off(ref s, ref s.guid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.Arg0));
        Assert.Equal(10, Off(ref s, ref s.sFromID));
        Assert.Equal(138, Off(ref s, ref s.sMsg));
        Assert.Equal(218, Off(ref s, ref s.sDate));
        Assert.Equal(250, Off(ref s, ref s.ItemType));
    }
    [Fact] public void sPouchPrize()
    {
        Assert.Equal(20, Unsafe.SizeOf<sPouchPrize>());
        var s = new sPouchPrize();
        Assert.Equal(0, Off(ref s, ref s.dwTid));
        Assert.Equal(4, Off(ref s, ref s.dwGuid));
        Assert.Equal(8, Off(ref s, ref s.iCount));
        Assert.Equal(12, Off(ref s, ref s.dwFlag1));
        Assert.Equal(16, Off(ref s, ref s.dwFlag2));
    }
    [Fact] public void sApproachResultData()
    {
        Assert.Equal(24, Unsafe.SizeOf<sApproachResultData>());
        var s = new sApproachResultData();
        Assert.Equal(0, Off(ref s, ref s.bExit));
        Assert.Equal(1, Off(ref s, ref s.dwGUID));
        Assert.Equal(5, Off(ref s, ref s.dwRealUID));
        Assert.Equal(9, Off(ref s, ref s.byRank));
        Assert.Equal(10, Off(ref s, ref s.dwPrizeCount));
        Assert.Equal(14, Off(ref s, ref s.dwRemainDistance));
        Assert.Equal(18, Off(ref s, ref s.dwRemainTime));
        Assert.Equal(22, Off(ref s, ref s.byRankPrize));
        Assert.Equal(23, Off(ref s, ref s.byLuckPrize));
    }
    [Fact] public void CUTIN_ANI_STYPEINFO()
    {
        Assert.Equal(184, Unsafe.SizeOf<CUTIN_ANI_STYPEINFO>());
        var s = new CUTIN_ANI_STYPEINFO();
        Assert.Equal(0, Off(ref s, ref s.PosType));
        Assert.Equal(4, Off(ref s, ref s.CharType));
        Assert.Equal(8, Off(ref s, ref s.BgType));
        Assert.Equal(12, Off(ref s, ref s.PatternType));
        Assert.Equal(16, Off(ref s, ref s.TextType));
        Assert.Equal(20, Off(ref s, ref s.OutType));
        Assert.Equal(24, Off(ref s, ref s.szCharTex));
        Assert.Equal(64, Off(ref s, ref s.szBgTex));
        Assert.Equal(104, Off(ref s, ref s.szPattern));
        Assert.Equal(144, Off(ref s, ref s.szText));
    }
    [Fact] public void GimmickDispositionInformation()
    {
        Assert.Equal(20, Unsafe.SizeOf<GimmickDispositionInformation>());
        var s = new GimmickDispositionInformation();
        Assert.Equal(0, Off(ref s, ref s.type));
        Assert.Equal(4, Off(ref s, ref s.index));
        Assert.Equal(8, Off(ref s, ref s.flag));
        Assert.Equal(12, Off(ref s, ref s.unknownC));
        Assert.Equal(16, Off(ref s, ref s.hole));
    }
    [Fact] public void sSCardAvilityPeriodInfo()
    {
        Assert.Equal(65, Unsafe.SizeOf<sSCardAvilityPeriodInfo>());
        var s = new sSCardAvilityPeriodInfo();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.tid));
        Assert.Equal(8, Off(ref s, ref s.partsTid));
        Assert.Equal(12, Off(ref s, ref s.partsUid));
        Assert.Equal(16, Off(ref s, ref s.Avility));
        Assert.Equal(20, Off(ref s, ref s.AvilityValue));
        Assert.Equal(24, Off(ref s, ref s.slotNum));
        Assert.Equal(28, Off(ref s, ref s.useStartTime));
        Assert.Equal(44, Off(ref s, ref s.useEndTime));
        Assert.Equal(60, Off(ref s, ref s.cardType));
        Assert.Equal(64, Off(ref s, ref s.valid));
    }
    [Fact] public void sCards()
    {
        Assert.Equal(58, Unsafe.SizeOf<sCards>());
        var s = new sCards();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.typeId));
        Assert.Equal(8, Off(ref s, ref s.reserved08));
        Assert.Equal(20, Off(ref s, ref s.count));
        Assert.Equal(24, Off(ref s, ref s.reserved18));
        Assert.Equal(56, Off(ref s, ref s.type));
        Assert.Equal(57, Off(ref s, ref s.reserved39));
    }
    [Fact] public void sItemAttachCard()
    {
        Assert.Equal(8, Unsafe.SizeOf<sItemAttachCard>());
        var s = new sItemAttachCard();
        Assert.Equal(0, Off(ref s, ref s.typeId));
        Assert.Equal(4, Off(ref s, ref s.id));
    }
    [Fact] public void sCaddieReportData()
    {
        Assert.Equal(127, Unsafe.SizeOf<sCaddieReportData>());
        var s = new sCaddieReportData();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.pang));
        Assert.Equal(12, Off(ref s, ref s.bonusPang));
        Assert.Equal(20, Off(ref s, ref s.roomType));
        Assert.Equal(24, Off(ref s, ref s.exp));
        Assert.Equal(28, Off(ref s, ref s.mascotTypeId));
        Assert.Equal(32, Off(ref s, ref s.premium));
        Assert.Equal(33, Off(ref s, ref s.pangItem));
        Assert.Equal(34, Off(ref s, ref s.level));
        Assert.Equal(36, Off(ref s, ref s.reserved24));
        Assert.Equal(38, Off(ref s, ref s.score));
        Assert.Equal(39, Off(ref s, ref s.awardFlag));
        Assert.Equal(40, Off(ref s, ref s.eventType));
        Assert.Equal(41, Off(ref s, ref s.reserved29));
        Assert.Equal(63, Off(ref s, ref s.nickname));
        Assert.Equal(85, Off(ref s, ref s.reserved55));
        Assert.Equal(89, Off(ref s, ref s.guildUID));
        Assert.Equal(93, Off(ref s, ref s.guildMark));
        Assert.Equal(105, Off(ref s, ref s.gameType));
        Assert.Equal(106, Off(ref s, ref s.reserved6a));
        Assert.Equal(109, Off(ref s, ref s.team));
        Assert.Equal(110, Off(ref s, ref s.eventFlag));
        Assert.Equal(111, Off(ref s, ref s.reserved6f));
    }
    [Fact] public void sRoomUserInfo()
    {
        Assert.Equal(18, Unsafe.SizeOf<sRoomUserInfo>());
        var s = new sRoomUserInfo();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.level));
        Assert.Equal(5, Off(ref s, ref s.Bits_hole));
        Assert.Equal(6, Off(ref s, ref s.capability));
        Assert.Equal(10, Off(ref s, ref s.reserved0a));
        Assert.Equal(14, Off(ref s, ref s.ladderPoint));
    }
    [Fact] public void sGuildMatchFlagInfo()
    {
        Assert.Equal(46, Unsafe.SizeOf<sGuildMatchFlagInfo>());
        var s = new sGuildMatchFlagInfo();
        Assert.Equal(0, Off(ref s, ref s.reserved));
    }
    [Fact] public void sMapEventInfo()
    {
        Assert.Equal(40, Unsafe.SizeOf<sMapEventInfo>());
        var s = new sMapEventInfo();
        Assert.Equal(0, Off(ref s, ref s.reserved));
    }
    [Fact] public void sBurnningSpCard()
    {
        Assert.Equal(20, Unsafe.SizeOf<sBurnningSpCard>());
        var s = new sBurnningSpCard();
        Assert.Equal(0, Off(ref s, ref s.reserved));
    }
    [Fact] public void GuildMemberInfo_t()
    {
        Assert.Equal(64, Unsafe.SizeOf<GuildMemberInfo_t>());
        var s = new GuildMemberInfo_t();
        Assert.Equal(0, Off(ref s, ref s.reserved));
    }
    [Fact] public void sFurniture_List()
    {
        Assert.Equal(27, Unsafe.SizeOf<sFurniture_List>());
        var s = new sFurniture_List();
        Assert.Equal(0, Off(ref s, ref s.id));
        Assert.Equal(4, Off(ref s, ref s.typeId));
        Assert.Equal(8, Off(ref s, ref s.reserved));
        Assert.Equal(10, Off(ref s, ref s.x));
        Assert.Equal(14, Off(ref s, ref s.y));
        Assert.Equal(18, Off(ref s, ref s.z));
        Assert.Equal(22, Off(ref s, ref s.r));
        Assert.Equal(26, Off(ref s, ref s.Bits_bArrange));
    }
    [Fact] public void sAwardItem()
    {
        Assert.Equal(8, Unsafe.SizeOf<sAwardItem>());
        var s = new sAwardItem();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.pang));
    }
    [Fact] public void sRealMyRoomAuthority()
    {
        Assert.Equal(107, Unsafe.SizeOf<sRealMyRoomAuthority>());
        var s = new sRealMyRoomAuthority();
        Assert.Equal(0, Off(ref s, ref s.ownerUID));
        Assert.Equal(4, Off(ref s, ref s.unknown4));
        Assert.Equal(6, Off(ref s, ref s.bPrivate));
        Assert.Equal(7, Off(ref s, ref s.password));
    }
    [Fact] public void sBuyItemResult()
    {
        Assert.Equal(38, Unsafe.SizeOf<sBuyItemResult>());
        var s = new sBuyItemResult();
        Assert.Equal(0, Off(ref s, ref s.Typeid));
        Assert.Equal(4, Off(ref s, ref s.guid));
        Assert.Equal(8, Off(ref s, ref s.Time));
        Assert.Equal(10, Off(ref s, ref s.ItemType));
        Assert.Equal(11, Off(ref s, ref s.Count));
        Assert.Equal(13, Off(ref s, ref s.endDate));
        Assert.Equal(29, Off(ref s, ref s.UccIndex));
    }
    [Fact] public void sBuyItem()
    {
        Assert.Equal(16, Unsafe.SizeOf<sBuyItem>());
        var s = new sBuyItem();
        Assert.Equal(0, Off(ref s, ref s.Idx));
        Assert.Equal(4, Off(ref s, ref s.TypeCode));
        Assert.Equal(8, Off(ref s, ref s.DayCount));
        Assert.Equal(10, Off(ref s, ref s.sChildItemIndex));
        Assert.Equal(12, Off(ref s, ref s.ItemCount));
    }
    [Fact] public void sTradeItem()
    {
        Assert.Equal(170, Unsafe.SizeOf<sTradeItem>());
        var s = new sTradeItem();
        Assert.Equal(0, Off(ref s, ref s.iIndex));
        Assert.Equal(4, Off(ref s, ref s.dwTid));
        Assert.Equal(8, Off(ref s, ref s.dwGuid));
        Assert.Equal(12, Off(ref s, ref s.iNum));
        Assert.Equal(16, Off(ref s, ref s.byItemType));
        Assert.Equal(17, Off(ref s, ref s.wTime));
        Assert.Equal(19, Off(ref s, ref s.i64Price));
        Assert.Equal(27, Off(ref s, ref s.dwUpgradeCost));
        Assert.Equal(31, Off(ref s, ref s.arrEnchant));
        Assert.Equal(41, Off(ref s, ref s.wFlagTradeLimit));
        Assert.Equal(43, Off(ref s, ref s.UccIndex));
        Assert.Equal(52, Off(ref s, ref s.Seq));
        Assert.Equal(54, Off(ref s, ref s.status));
        Assert.Equal(55, Off(ref s, ref s.attachCardTid));
        Assert.Equal(103, Off(ref s, ref s.CharacterSlotNum));
        Assert.Equal(105, Off(ref s, ref s.CaddieSlotNum));
        Assert.Equal(107, Off(ref s, ref s.ItemName));
        Assert.Equal(148, Off(ref s, ref s.CopierNick));
    }
    [Fact] public void sStallSlot()
    {
        Assert.Equal(193, Unsafe.SizeOf<sStallSlot>());
        var s = new sStallSlot();
        Assert.Equal(0, Off(ref s, ref s.stallKey));
        Assert.Equal(4, Off(ref s, ref s.Idx));
        Assert.Equal(5, Off(ref s, ref s.itemData));
        Assert.Equal(175, Off(ref s, ref s.time));
        Assert.Equal(191, Off(ref s, ref s.IsPermanence));
        Assert.Equal(192, Off(ref s, ref s.IsValid));
    }
    [Fact] public void sStall()
    {
        Assert.Equal(2343, Unsafe.SizeOf<sStall>());
        var s = new sStall();
        Assert.Equal(0, Off(ref s, ref s.typeID));
        Assert.Equal(4, Off(ref s, ref s.stallKey));
        Assert.Equal(8, Off(ref s, ref s.state));
        Assert.Equal(9, Off(ref s, ref s.maxSlotNum));
        Assert.Equal(10, Off(ref s, ref s.useSlotNum));
        Assert.Equal(11, Off(ref s, ref s.slotList));
        Assert.Equal(2327, Off(ref s, ref s.time));
    }
    [Fact] public void sStoredItemInfo()
    {
        Assert.Equal(174, Unsafe.SizeOf<sStoredItemInfo>());
        var s = new sStoredItemInfo();
        Assert.Equal(0, Off(ref s, ref s.dwStorageID));
        Assert.Equal(4, Off(ref s, ref s.itemInfo));
    }
    [Fact] public void sSaleItem()
    {
        Assert.Equal(94, Unsafe.SizeOf<sSaleItem>());
        var s = new sSaleItem();
        Assert.Equal(0, Off(ref s, ref s.ownerUID));
        Assert.Equal(4, Off(ref s, ref s.nickname));
        Assert.Equal(26, Off(ref s, ref s.typeId));
        Assert.Equal(30, Off(ref s, ref s.price));
        Assert.Equal(38, Off(ref s, ref s.count));
        Assert.Equal(40, Off(ref s, ref s.bOpen));
        Assert.Equal(41, Off(ref s, ref s.reserved));
    }
    [Fact] public void sCardStack()
    {
        Assert.Equal(14, Unsafe.SizeOf<sCardStack>());
        var s = new sCardStack();
        Assert.Equal(0, Off(ref s, ref s.uid));
        Assert.Equal(4, Off(ref s, ref s.typeId));
        Assert.Equal(8, Off(ref s, ref s.count));
        Assert.Equal(12, Off(ref s, ref s.bValid));
        Assert.Equal(13, Off(ref s, ref s.unknownD));
    }
    [Fact] public void IFF_ITEM_COMMON()
    {
        Assert.Equal(144, Unsafe.SizeOf<IFF_ITEM_COMMON>());
        var s = new IFF_ITEM_COMMON();
        Assert.Equal(0, Off(ref s, ref s.Final));
        Assert.Equal(4, Off(ref s, ref s.TypeId));
        Assert.Equal(8, Off(ref s, ref s.Name));
        Assert.Equal(48, Off(ref s, ref s.Bits_Level));
        Assert.Equal(49, Off(ref s, ref s.Icon));
        Assert.Equal(92, Off(ref s, ref s.Price));
        Assert.Equal(96, Off(ref s, ref s.SalePrice));
        Assert.Equal(100, Off(ref s, ref s.UsedPrice));
        Assert.Equal(104, Off(ref s, ref s.Bits_IsCash));
        Assert.Equal(105, Off(ref s, ref s.Bits_New));
        Assert.Equal(106, Off(ref s, ref s.TimeFlag));
        Assert.Equal(107, Off(ref s, ref s.Time));
        Assert.Equal(108, Off(ref s, ref s.Point));
        Assert.Equal(112, Off(ref s, ref s.saleStart));
        Assert.Equal(128, Off(ref s, ref s.saleEnd));
    }
    [Fact] public void Iff_sChar()
    {
        Assert.Equal(372, Unsafe.SizeOf<Iff.sChar>());
        var s = new Iff.sChar();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.HairTex));
        Assert.Equal(224, Off(ref s, ref s.ShirtsTex));
        Assert.Equal(264, Off(ref s, ref s.FaceTex));
        Assert.Equal(304, Off(ref s, ref s.Attr));
        Assert.Equal(314, Off(ref s, ref s.nParts));
        Assert.Equal(315, Off(ref s, ref s.nAcsries));
        Assert.Equal(316, Off(ref s, ref s.ClubType));
        Assert.Equal(320, Off(ref s, ref s.ClubScale));
        Assert.Equal(324, Off(ref s, ref s.PCL));
        Assert.Equal(329, Off(ref s, ref s.Mtn30sWinner));
    }
    [Fact] public void Iff_sPart()
    {
        Assert.Equal(516, Unsafe.SizeOf<Iff.sPart>());
        var s = new Iff.sPart();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.Category));
        Assert.Equal(188, Off(ref s, ref s.PosMask));
        Assert.Equal(192, Off(ref s, ref s.HideMask));
        Assert.Equal(196, Off(ref s, ref s.Tex));
        Assert.Equal(316, Off(ref s, ref s.OrgTex));
        Assert.Equal(436, Off(ref s, ref s.Attr));
        Assert.Equal(446, Off(ref s, ref s.Slot));
        Assert.Equal(456, Off(ref s, ref s.EquippableWith));
        Assert.Equal(496, Off(ref s, ref s.SubPart));
        Assert.Equal(504, Off(ref s, ref s.CharacterSlot));
        Assert.Equal(506, Off(ref s, ref s.CaddieSlot));
        Assert.Equal(508, Off(ref s, ref s.RentalPrice));
        Assert.Equal(512, Off(ref s, ref s.Beginner));
        Assert.Equal(514, Off(ref s, ref s.Point));
    }
    [Fact] public void Iff_sClub()
    {
        Assert.Equal(196, Unsafe.SizeOf<Iff.sClub>());
        var s = new Iff.sClub();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.Type));
        Assert.Equal(186, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sClubSet()
    {
        Assert.Equal(180, Unsafe.SizeOf<Iff.sClubSet>());
        var s = new Iff.sClubSet();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.ClubIds));
        Assert.Equal(160, Off(ref s, ref s.Attr));
        Assert.Equal(170, Off(ref s, ref s.Slot));
    }
    [Fact] public void Iff_sBall()
    {
        Assert.Equal(764, Unsafe.SizeOf<Iff.sBall>());
        var s = new Iff.sBall();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.Bound));
        Assert.Equal(188, Off(ref s, ref s.Roll));
        Assert.Equal(192, Off(ref s, ref s.Fx));
        Assert.Equal(472, Off(ref s, ref s.FxBone));
        Assert.Equal(752, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sCaddie()
    {
        Assert.Equal(200, Unsafe.SizeOf<Iff.sCaddie>());
        var s = new Iff.sCaddie();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.MonthlyFee));
        Assert.Equal(148, Off(ref s, ref s.Data));
        Assert.Equal(188, Off(ref s, ref s.Attr));
    }
    [Fact] public void Iff_sCadItem()
    {
        Assert.Equal(236, Unsafe.SizeOf<Iff.sCadItem>());
        var s = new Iff.sCadItem();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.FaceTex));
        Assert.Equal(184, Off(ref s, ref s.BodyTex));
        Assert.Equal(224, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sSetItem()
    {
        Assert.Equal(220, Unsafe.SizeOf<Iff.sSetItem>());
        var s = new Iff.sSetItem();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.nElems));
        Assert.Equal(148, Off(ref s, ref s.ElemIds));
        Assert.Equal(188, Off(ref s, ref s.ElemNum));
        Assert.Equal(208, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sCourse()
    {
        Assert.Equal(312, Unsafe.SizeOf<Iff.sCourse>());
        var s = new Iff.sCourse();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.AmbientSnd));
        Assert.Equal(224, Off(ref s, ref s.Bits_Difficulty));
        Assert.Equal(225, Off(ref s, ref s.TexProp));
        Assert.Equal(268, Off(ref s, ref s.Slope));
        Assert.Equal(272, Off(ref s, ref s.SkyFx));
    }
    [Fact] public void Iff_sMatch()
    {
        Assert.Equal(332, Unsafe.SizeOf<Iff.sMatch>());
        var s = new Iff.sMatch();
        Assert.Equal(0, Off(ref s, ref s.Final));
        Assert.Equal(4, Off(ref s, ref s.TypeId));
        Assert.Equal(8, Off(ref s, ref s.Name));
        Assert.Equal(88, Off(ref s, ref s.Level));
        Assert.Equal(89, Off(ref s, ref s.Icon));
    }
    [Fact] public void Iff_sTitle()
    {
        Assert.Equal(88, Unsafe.SizeOf<Iff.sTitle>());
        var s = new Iff.sTitle();
        Assert.Equal(0, Off(ref s, ref s.Final));
        Assert.Equal(4, Off(ref s, ref s.TypeId));
        Assert.Equal(8, Off(ref s, ref s.Name));
        Assert.Equal(48, Off(ref s, ref s.Icon));
    }
    [Fact] public void Iff_sEnchant()
    {
        Assert.Equal(16, Unsafe.SizeOf<Iff.sEnchant>());
        var s = new Iff.sEnchant();
        Assert.Equal(0, Off(ref s, ref s.Final));
        Assert.Equal(4, Off(ref s, ref s.TypeId));
        Assert.Equal(8, Off(ref s, ref s.ReqdPang));
        Assert.Equal(12, Off(ref s, ref s.ReqdLevel));
    }
    [Fact] public void Iff_sSkin()
    {
        Assert.Equal(196, Unsafe.SizeOf<Iff.sSkin>());
        var s = new Iff.sSkin();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Tex));
        Assert.Equal(184, Off(ref s, ref s.HScroll));
        Assert.Equal(185, Off(ref s, ref s.VScroll));
        Assert.Equal(186, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sHairStyle()
    {
        Assert.Equal(148, Unsafe.SizeOf<Iff.sHairStyle>());
        var s = new Iff.sHairStyle();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.cHairID));
        Assert.Equal(145, Off(ref s, ref s.cCharID));
    }
    [Fact] public void Iff_sChildItem()
    {
        Assert.Equal(72, Unsafe.SizeOf<Iff.sChildItem>());
        var s = new Iff.sChildItem();
        Assert.Equal(0, Off(ref s, ref s.Final));
        Assert.Equal(4, Off(ref s, ref s.TypeId));
        Assert.Equal(8, Off(ref s, ref s.Name));
        Assert.Equal(48, Off(ref s, ref s.Bits_Level));
        Assert.Equal(49, Off(ref s, ref s.Bits_IsDisplay));
        Assert.Equal(52, Off(ref s, ref s.NumberPrice));
        Assert.Equal(56, Off(ref s, ref s.NumberFlag));
        Assert.Equal(58, Off(ref s, ref s.Number));
        Assert.Equal(60, Off(ref s, ref s.TimePrice));
        Assert.Equal(64, Off(ref s, ref s.TimeFlag));
        Assert.Equal(66, Off(ref s, ref s.Time));
        Assert.Equal(68, Off(ref s, ref s.FailPercent));
    }
    [Fact] public void Iff_sItem()
    {
        Assert.Equal(200, Unsafe.SizeOf<Iff.sItem>());
        var s = new Iff.sItem();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Bits_RandomBox));
        Assert.Equal(148, Off(ref s, ref s.Data));
        Assert.Equal(188, Off(ref s, ref s.COM));
        Assert.Equal(198, Off(ref s, ref s.Point));
    }
    [Fact] public void Iff_sMascot()
    {
        Assert.Equal(252, Unsafe.SizeOf<Iff.sMascot>());
        var s = new Iff.sMascot();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.MsgTex));
        Assert.Equal(224, Off(ref s, ref s.COM));
        Assert.Equal(229, Off(ref s, ref s.Attr));
        Assert.Equal(234, Off(ref s, ref s.DriveUp));
        Assert.Equal(236, Off(ref s, ref s.ItemDropUp));
        Assert.Equal(238, Off(ref s, ref s.ComboUp));
        Assert.Equal(240, Off(ref s, ref s.PangUp));
        Assert.Equal(242, Off(ref s, ref s.ExpUp));
        Assert.Equal(244, Off(ref s, ref s.ItemSlot));
        Assert.Equal(245, Off(ref s, ref s.ShowMsg));
        Assert.Equal(248, Off(ref s, ref s.MsgFee));
    }
    [Fact] public void Iff_sAuxPart()
    {
        Assert.Equal(176, Unsafe.SizeOf<Iff.sAuxPart>());
        var s = new Iff.sAuxPart();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.COM));
        Assert.Equal(154, Off(ref s, ref s.Attr));
        Assert.Equal(159, Off(ref s, ref s.Slot));
        Assert.Equal(164, Off(ref s, ref s.DriveUp));
        Assert.Equal(166, Off(ref s, ref s.ItemDropUp));
        Assert.Equal(168, Off(ref s, ref s.ComboUp));
        Assert.Equal(170, Off(ref s, ref s.PangUp));
        Assert.Equal(172, Off(ref s, ref s.ExpUp));
    }
    [Fact] public void Iff_sQuestDrop()
    {
        Assert.Equal(244, Unsafe.SizeOf<Iff.sQuestDrop>());
        var s = new Iff.sQuestDrop();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.dropStart));
        Assert.Equal(160, Off(ref s, ref s.dropEnd));
        Assert.Equal(176, Off(ref s, ref s.dropFx));
        Assert.Equal(216, Off(ref s, ref s.dropCycle));
        Assert.Equal(218, Off(ref s, ref s.holesToPlay));
        Assert.Equal(238, Off(ref s, ref s.mapDiff));
        Assert.Equal(239, Off(ref s, ref s.holeDrop));
        Assert.Equal(240, Off(ref s, ref s.timeDrop));
    }
    [Fact] public void Iff_sCard()
    {
        Assert.Equal(328, Unsafe.SizeOf<Iff.sCard>());
        var s = new Iff.sCard();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.RareType));
        Assert.Equal(145, Off(ref s, ref s.Image));
        Assert.Equal(186, Off(ref s, ref s.COM));
        Assert.Equal(196, Off(ref s, ref s.Avility));
        Assert.Equal(198, Off(ref s, ref s.AvilityValue));
        Assert.Equal(200, Off(ref s, ref s.SubIcon));
        Assert.Equal(240, Off(ref s, ref s.SlotImg));
        Assert.Equal(280, Off(ref s, ref s.BuffImg));
        Assert.Equal(320, Off(ref s, ref s.UseTime));
        Assert.Equal(322, Off(ref s, ref s.Volume));
        Assert.Equal(324, Off(ref s, ref s.CardIndex));
    }
    [Fact] public void Iff_sFurniture()
    {
        Assert.Equal(464, Unsafe.SizeOf<Iff.sFurniture>());
        var s = new Iff.sFurniture();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.Data));
        Assert.Equal(184, Off(ref s, ref s.Num));
        Assert.Equal(186, Off(ref s, ref s.IsOwn));
        Assert.Equal(188, Off(ref s, ref s.IsMove));
        Assert.Equal(190, Off(ref s, ref s.IsFunction));
        Assert.Equal(192, Off(ref s, ref s.Etc));
        Assert.Equal(196, Off(ref s, ref s.Pos));
        Assert.Equal(212, Off(ref s, ref s.Tex));
        Assert.Equal(332, Off(ref s, ref s.OrgTex));
        Assert.Equal(452, Off(ref s, ref s.COM));
        Assert.Equal(462, Off(ref s, ref s.UseTime));
    }
    [Fact] public void Iff_sOfflineShop()
    {
        Assert.Equal(200, Unsafe.SizeOf<Iff.sOfflineShop>());
        var s = new Iff.sOfflineShop();
        Assert.Equal(0, Off(ref s, ref s.c));
        Assert.Equal(144, Off(ref s, ref s.nElems));
        Assert.Equal(148, Off(ref s, ref s.ElemIds));
        Assert.Equal(188, Off(ref s, ref s.COM));
    }
    [Fact] public void Iff_sDesc()
    {
        Assert.Equal(516, Unsafe.SizeOf<Iff.sDesc>());
        var s = new Iff.sDesc();
        Assert.Equal(0, Off(ref s, ref s.TypeId));
        Assert.Equal(4, Off(ref s, ref s.Desc));
    }
    [Fact] public void Iff_sRandomBox()
    {
        Assert.Equal(228, Unsafe.SizeOf<Iff.sRandomBox>());
        var s = new Iff.sRandomBox();
        Assert.Equal(0, Off(ref s, ref s.active));
        Assert.Equal(1, Off(ref s, ref s.unknown01));
        Assert.Equal(36, Off(ref s, ref s.boxTypeId));
        Assert.Equal(40, Off(ref s, ref s.kind));
        Assert.Equal(44, Off(ref s, ref s.typeId));
        Assert.Equal(48, Off(ref s, ref s.unknown30));
        Assert.Equal(56, Off(ref s, ref s.checkTypeId));
        Assert.Equal(60, Off(ref s, ref s.unknown3C));
    }
    [Fact] public void Iff_sRandomRecycle()
    {
        Assert.Equal(16, Unsafe.SizeOf<Iff.sRandomRecycle>());
        var s = new Iff.sRandomRecycle();
        Assert.Equal(0, Off(ref s, ref s.uiRandSeq));
        Assert.Equal(4, Off(ref s, ref s.uiTypeId));
        Assert.Equal(8, Off(ref s, ref s.uiCount));
        Assert.Equal(12, Off(ref s, ref s.uiProbs));
    }
    [Fact] public void Iff_sNonVisibleItem()
    {
        Assert.Equal(44, Unsafe.SizeOf<Iff.sNonVisibleItem>());
        var s = new Iff.sNonVisibleItem();
        Assert.Equal(0, Off(ref s, ref s.active));
        Assert.Equal(4, Off(ref s, ref s.type));
        Assert.Equal(8, Off(ref s, ref s.typeId));
        Assert.Equal(12, Off(ref s, ref s.start));
        Assert.Equal(28, Off(ref s, ref s.end));
    }
    [Fact] public void Iff_sSubscriptionItem()
    {
        Assert.Equal(44, Unsafe.SizeOf<Iff.sSubscriptionItem>());
        var s = new Iff.sSubscriptionItem();
        Assert.Equal(0, Off(ref s, ref s.active));
        Assert.Equal(4, Off(ref s, ref s.type));
        Assert.Equal(8, Off(ref s, ref s.typeId));
        Assert.Equal(12, Off(ref s, ref s.start));
        Assert.Equal(28, Off(ref s, ref s.end));
    }
    [Fact] public void Iff_sSpecialPrizeItem()
    {
        Assert.Equal(12, Unsafe.SizeOf<Iff.sSpecialPrizeItem>());
        var s = new Iff.sSpecialPrizeItem();
        Assert.Equal(0, Off(ref s, ref s.typeId));
        Assert.Equal(4, Off(ref s, ref s.ability));
        Assert.Equal(8, Off(ref s, ref s.rate));
    }
    [Fact] public void Iff_sCadieMagicBox()
    {
        Assert.Equal(104, Unsafe.SizeOf<Iff.sCadieMagicBox>());
        var s = new Iff.sCadieMagicBox();
        Assert.Equal(0, Off(ref s, ref s.uiNumber));
        Assert.Equal(4, Off(ref s, ref s.bFinal));
        Assert.Equal(8, Off(ref s, ref s.uiCategory));
        Assert.Equal(12, Off(ref s, ref s.iCharacter));
        Assert.Equal(16, Off(ref s, ref s.iLevel));
        Assert.Equal(20, Off(ref s, ref s.uiOutput));
        Assert.Equal(24, Off(ref s, ref s.uiOutputCount));
        Assert.Equal(28, Off(ref s, ref s.uiElem));
        Assert.Equal(44, Off(ref s, ref s.uiElemCount));
        Assert.Equal(60, Off(ref s, ref s.uiRandSeq));
        Assert.Equal(64, Off(ref s, ref s.szRandName));
    }
    [Fact] public void Iff_sFurnitureAbility()
    {
        Assert.Equal(60, Unsafe.SizeOf<Iff.sFurnitureAbility>());
        var s = new Iff.sFurnitureAbility();
        Assert.Equal(0, Off(ref s, ref s.bFinal));
        Assert.Equal(1, Off(ref s, ref s.btAbilityType));
        Assert.Equal(4, Off(ref s, ref s.dwFurnitureTID));
        Assert.Equal(8, Off(ref s, ref s.btSuccessType));
        Assert.Equal(12, Off(ref s, ref s.iStayTime));
        Assert.Equal(16, Off(ref s, ref s.btEffectType));
        Assert.Equal(20, Off(ref s, ref s.dwSetInTID));
        Assert.Equal(24, Off(ref s, ref s.iMaxCountAtFurniture));
        Assert.Equal(28, Off(ref s, ref s.stStart));
        Assert.Equal(44, Off(ref s, ref s.dwDuringTime));
        Assert.Equal(48, Off(ref s, ref s.dwPutOutTID));
        Assert.Equal(52, Off(ref s, ref s.iProbability));
        Assert.Equal(56, Off(ref s, ref s.iMaxCountAtUser));
    }
    [Fact] public void Iff_sTikiOutputTable()
    {
        Assert.Equal(52, Unsafe.SizeOf<Iff.sTikiOutputTable>());
        var s = new Iff.sTikiOutputTable();
        Assert.Equal(0, Off(ref s, ref s.uiIndex));
        Assert.Equal(4, Off(ref s, ref s.bFinal));
        Assert.Equal(5, Off(ref s, ref s.strCategory));
        Assert.Equal(40, Off(ref s, ref s.uiTypeID));
        Assert.Equal(44, Off(ref s, ref s.uiCount));
        Assert.Equal(48, Off(ref s, ref s.uiRate));
    }
    [Fact] public void Iff_sTikiPointTable()
    {
        Assert.Equal(48, Unsafe.SizeOf<Iff.sTikiPointTable>());
        var s = new Iff.sTikiPointTable();
        Assert.Equal(0, Off(ref s, ref s.uiIndex));
        Assert.Equal(4, Off(ref s, ref s.bFinal));
        Assert.Equal(5, Off(ref s, ref s.strCategory));
        Assert.Equal(40, Off(ref s, ref s.uiMin));
        Assert.Equal(44, Off(ref s, ref s.uiMax));
    }
    [Fact] public void Iff_sTikiSpecialRecipe()
    {
        Assert.Equal(60, Unsafe.SizeOf<Iff.sTikiSpecialRecipe>());
        var s = new Iff.sTikiSpecialRecipe();
        Assert.Equal(0, Off(ref s, ref s.uiIndex));
        Assert.Equal(4, Off(ref s, ref s.bFinal));
        Assert.Equal(5, Off(ref s, ref s.strCategory));
        Assert.Equal(40, Off(ref s, ref s.uiElemCount));
        Assert.Equal(44, Off(ref s, ref s.uiElem));
    }
}
